<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <AssemblyTitle>TACATDP Deployment Package</AssemblyTitle>
    <Product>TACATDP Deployment Package</Product>
    <Copyright>Copyright CRDB Bank PLC 2026</Copyright>
    <AssemblyName>Tacatdp.DeploymentPackage</AssemblyName>
    <RootNamespace>Tacatdp.DeploymentPackage</RootNamespace>
    <Version>1.0.3</Version>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.PowerApps.MSBuild.PDPackage" Version="1.*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CrmSdk.XrmTooling.CoreAssembly" Version="9.1.0.79" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CrmSdk.XrmTooling.PackageDeployment" Version="9.1.0.74" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CrmSdk.CoreAssemblies" Version="9.0.2.60" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.ComponentModel.Composition" />
    <Reference Include="System.Web.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <PdSolution Include="DeploymentAssets/Solutions/*.zip">
      <PublishWorkflowsAndActivatePlugins>false</PublishWorkflowsAndActivatePlugins>
      <OverwriteUnmanagedCustomizations>false</OverwriteUnmanagedCustomizations>
    </PdSolution>
  </ItemGroup>
</Project>
