#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Active new-user invitation delivery mode. Codes: ManualCode=100000000, Email=100000001.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum mp_notificationdeliverysetting_mp_deliverymode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	ManualCode = 100000000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Email = 100000001,
}

/// <summary>
/// Mailbox readiness. Codes: NotConfigured=100000000, PendingAdminSetup=100000001, Approved=100000002, TestedAndEnabled=100000003, Failed=100000004.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum mp_notificationdeliverysetting_mp_mailboxstatus
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	NotConfigured = 100000000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	PendingAdminSetup = 100000001,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Approved = 100000002,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	TestedAndEnabled = 100000003,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Failed = 100000004,
}

/// <summary>
/// Status of the NotificationDeliverySettings
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum mp_notificationdeliverysetting_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Reason for the status of the NotificationDeliverySettings
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum mp_notificationdeliverysetting_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 2,
}

/// <summary>
/// Administrator-owned configuration record describing how onboarding invitations and assignment notifications are delivered.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("mp_notificationdeliverysetting")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class mp_NotificationDeliverySetting : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
				/// <summary>
		/// Available fields, a the time of codegen, for the mp_notificationdeliverysetting entity
		/// </summary>
		public partial class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedByYomiName = "createdbyyominame";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedByYomiName = "modifiedbyyominame";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string mp_DeliveryMode = "mp_deliverymode";
			public const string mp_deliverymodeName = "mp_deliverymodename";
			public const string mp_Instructions = "mp_instructions";
			public const string mp_LastTestedAt = "mp_lasttestedat";
			public const string mp_LastTestResult = "mp_lasttestresult";
			public const string mp_MailboxStatus = "mp_mailboxstatus";
			public const string mp_mailboxstatusName = "mp_mailboxstatusname";
			public const string mp_NativeInvitationWorkflowId = "mp_nativeinvitationworkflowid";
			public const string mp_NotificationDeliverySettingId = "mp_notificationdeliverysettingid";
			public const string Id = "mp_notificationdeliverysettingid";
			public const string mp_SenderMailbox = "mp_sendermailbox";
			public const string mp_SettingKey = "mp_settingkey";
			public const string mp_UpdatedAt = "mp_updatedat";
			public const string mp_UpdatedByEmail = "mp_updatedbyemail";
			public const string OrganizationId = "organizationid";
			public const string OrganizationIdName = "organizationidname";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string statecode = "statecode";
			public const string statecodeName = "statecodename";
			public const string statuscode = "statuscode";
			public const string statuscodeName = "statuscodename";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
		}
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public mp_NotificationDeliverySetting() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "mp_notificationdeliverysetting";
	
	public const string EntityLogicalCollectionName = "mp_notificationdeliverysettings";
	
	public const string EntitySetName = "mp_notificationdeliverysettings";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
	public string CreatedByName
	{
		get
		{
			if (this.FormattedValues.Contains("createdby"))
			{
				return this.FormattedValues["createdby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
	public string CreatedByYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("createdby"))
			{
				return this.FormattedValues["createdby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
	public string CreatedOnBehalfByName
	{
		get
		{
			if (this.FormattedValues.Contains("createdonbehalfby"))
			{
				return this.FormattedValues["createdonbehalfby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
	public string CreatedOnBehalfByYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("createdonbehalfby"))
			{
				return this.FormattedValues["createdonbehalfby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
	public string ModifiedByName
	{
		get
		{
			if (this.FormattedValues.Contains("modifiedby"))
			{
				return this.FormattedValues["modifiedby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
	public string ModifiedByYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("modifiedby"))
			{
				return this.FormattedValues["modifiedby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
	public string ModifiedOnBehalfByName
	{
		get
		{
			if (this.FormattedValues.Contains("modifiedonbehalfby"))
			{
				return this.FormattedValues["modifiedonbehalfby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
	public string ModifiedOnBehalfByYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("modifiedonbehalfby"))
			{
				return this.FormattedValues["modifiedonbehalfby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Active new-user invitation delivery mode. Codes: ManualCode=100000000, Email=100000001.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_deliverymode")]
	public virtual mp_notificationdeliverysetting_mp_deliverymode? mp_DeliveryMode
	{
		get
		{
			return ((mp_notificationdeliverysetting_mp_deliverymode?)(EntityOptionSetEnum.GetEnum(this, "mp_deliverymode")));
		}
		set
		{
			this.OnPropertyChanging("mp_DeliveryMode");
			this.SetAttributeValue("mp_deliverymode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("mp_DeliveryMode");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_deliverymodename")]
	public string mp_deliverymodeName
	{
		get
		{
			if (this.FormattedValues.Contains("mp_deliverymode"))
			{
				return this.FormattedValues["mp_deliverymode"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Administrator-facing operational note for the selected delivery mode.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_instructions")]
	public string mp_Instructions
	{
		get
		{
			return this.GetAttributeValue<string>("mp_instructions");
		}
		set
		{
			this.OnPropertyChanging("mp_Instructions");
			this.SetAttributeValue("mp_instructions", value);
			this.OnPropertyChanged("mp_Instructions");
		}
	}
	
	/// <summary>
	/// Last mailbox or delivery smoke-test timestamp.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_lasttestedat")]
	public System.Nullable<System.DateTime> mp_LastTestedAt
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("mp_lasttestedat");
		}
		set
		{
			this.OnPropertyChanging("mp_LastTestedAt");
			this.SetAttributeValue("mp_lasttestedat", value);
			this.OnPropertyChanged("mp_LastTestedAt");
		}
	}
	
	/// <summary>
	/// Business-readable readiness or smoke-test result. Do not store credentials or token-bearing URLs.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_lasttestresult")]
	public string mp_LastTestResult
	{
		get
		{
			return this.GetAttributeValue<string>("mp_lasttestresult");
		}
		set
		{
			this.OnPropertyChanging("mp_LastTestResult");
			this.SetAttributeValue("mp_lasttestresult", value);
			this.OnPropertyChanged("mp_LastTestResult");
		}
	}
	
	/// <summary>
	/// Mailbox readiness. Codes: NotConfigured=100000000, PendingAdminSetup=100000001, Approved=100000002, TestedAndEnabled=100000003, Failed=100000004.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_mailboxstatus")]
	public virtual mp_notificationdeliverysetting_mp_mailboxstatus? mp_MailboxStatus
	{
		get
		{
			return ((mp_notificationdeliverysetting_mp_mailboxstatus?)(EntityOptionSetEnum.GetEnum(this, "mp_mailboxstatus")));
		}
		set
		{
			this.OnPropertyChanging("mp_MailboxStatus");
			this.SetAttributeValue("mp_mailboxstatus", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("mp_MailboxStatus");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_mailboxstatusname")]
	public string mp_mailboxstatusName
	{
		get
		{
			if (this.FormattedValues.Contains("mp_mailboxstatus"))
			{
				return this.FormattedValues["mp_mailboxstatus"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Native Power Pages Send Invitation workflow id validated by administrator.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_nativeinvitationworkflowid")]
	public string mp_NativeInvitationWorkflowId
	{
		get
		{
			return this.GetAttributeValue<string>("mp_nativeinvitationworkflowid");
		}
		set
		{
			this.OnPropertyChanging("mp_NativeInvitationWorkflowId");
			this.SetAttributeValue("mp_nativeinvitationworkflowid", value);
			this.OnPropertyChanged("mp_NativeInvitationWorkflowId");
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_notificationdeliverysettingid")]
	public System.Nullable<System.Guid> mp_NotificationDeliverySettingId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("mp_notificationdeliverysettingid");
		}
		set
		{
			this.OnPropertyChanging("mp_NotificationDeliverySettingId");
			this.SetAttributeValue("mp_notificationdeliverysettingid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("mp_NotificationDeliverySettingId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_notificationdeliverysettingid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.mp_NotificationDeliverySettingId = value;
		}
	}
	
	/// <summary>
	/// Approved sender mailbox address when mailbox delivery is enabled.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_sendermailbox")]
	public string mp_SenderMailbox
	{
		get
		{
			return this.GetAttributeValue<string>("mp_sendermailbox");
		}
		set
		{
			this.OnPropertyChanging("mp_SenderMailbox");
			this.SetAttributeValue("mp_sendermailbox", value);
			this.OnPropertyChanged("mp_SenderMailbox");
		}
	}
	
	/// <summary>
	/// Stable singleton key. Use onboarding-delivery for the active onboarding configuration.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_settingkey")]
	public string mp_SettingKey
	{
		get
		{
			return this.GetAttributeValue<string>("mp_settingkey");
		}
		set
		{
			this.OnPropertyChanging("mp_SettingKey");
			this.SetAttributeValue("mp_settingkey", value);
			this.OnPropertyChanged("mp_SettingKey");
		}
	}
	
	/// <summary>
	/// Portal configuration update timestamp.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_updatedat")]
	public System.Nullable<System.DateTime> mp_UpdatedAt
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("mp_updatedat");
		}
		set
		{
			this.OnPropertyChanging("mp_UpdatedAt");
			this.SetAttributeValue("mp_updatedat", value);
			this.OnPropertyChanged("mp_UpdatedAt");
		}
	}
	
	/// <summary>
	/// Signed-in administrator email that last updated the configuration from the portal.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_updatedbyemail")]
	public string mp_UpdatedByEmail
	{
		get
		{
			return this.GetAttributeValue<string>("mp_updatedbyemail");
		}
		set
		{
			this.OnPropertyChanging("mp_UpdatedByEmail");
			this.SetAttributeValue("mp_updatedbyemail", value);
			this.OnPropertyChanged("mp_UpdatedByEmail");
		}
	}
	
	/// <summary>
	/// Unique identifier for the organization
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
	public Microsoft.Xrm.Sdk.EntityReference OrganizationId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationidname")]
	public string OrganizationIdName
	{
		get
		{
			if (this.FormattedValues.Contains("organizationid"))
			{
				return this.FormattedValues["organizationid"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// Status of the NotificationDeliverySettings
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual mp_notificationdeliverysetting_statecode? statecode
	{
		get
		{
			return ((mp_notificationdeliverysetting_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
	public string statecodeName
	{
		get
		{
			if (this.FormattedValues.Contains("statecode"))
			{
				return this.FormattedValues["statecode"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Reason for the status of the NotificationDeliverySettings
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual mp_notificationdeliverysetting_statuscode? statuscode
	{
		get
		{
			return ((mp_notificationdeliverysetting_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
	public string statuscodeName
	{
		get
		{
			if (this.FormattedValues.Contains("statuscode"))
			{
				return this.FormattedValues["statuscode"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Time zone code that was in use when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
}
#pragma warning restore CS1591
