#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// The type of invitation.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum adx_invitation_adx_type
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Single = 756150000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Group = 756150001,
}

/// <summary>
/// Status of the Invitation
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum adx_invitation_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Reason for the status of the Invitation
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum adx_invitation_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	New = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Sent = 756150000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Redeemed = 756150001,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 2,
}

/// <summary>
/// Send invitations to existing contacts or email addresses and assign them to web roles upon redemption.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("adx_invitation")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class adx_invitation : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
				/// <summary>
		/// Available fields, a the time of codegen, for the adx_invitation entity
		/// </summary>
		public partial class Fields
		{
			public const string adx_assignToAccount = "adx_assigntoaccount";
			public const string adx_assignToAccountName = "adx_assigntoaccountname";
			public const string adx_assignToAccountYomiName = "adx_assigntoaccountyominame";
			public const string adx_expiryDate = "adx_expirydate";
			public const string adx_invitationCode = "adx_invitationcode";
			public const string adx_invitationId = "adx_invitationid";
			public const string Id = "adx_invitationid";
			public const string adx_inviteContact = "adx_invitecontact";
			public const string adx_inviteContactName = "adx_invitecontactname";
			public const string adx_inviteContactYomiName = "adx_invitecontactyominame";
			public const string adx_invitercontact = "adx_invitercontact";
			public const string adx_invitercontactName = "adx_invitercontactname";
			public const string adx_invitercontactYomiName = "adx_invitercontactyominame";
			public const string adx_maximumRedemptions = "adx_maximumredemptions";
			public const string adx_name = "adx_name";
			public const string adx_redeemedContact = "adx_redeemedcontact";
			public const string adx_redeemedContactName = "adx_redeemedcontactname";
			public const string adx_redeemedContactYomiName = "adx_redeemedcontactyominame";
			public const string adx_redemptions = "adx_redemptions";
			public const string adx_redemptionWorkflow = "adx_redemptionworkflow";
			public const string adx_redemptionWorkflowName = "adx_redemptionworkflowname";
			public const string adx_type = "adx_type";
			public const string adx_typeName = "adx_typename";
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedByYomiName = "createdbyyominame";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedByYomiName = "modifiedbyyominame";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string mspp_websiteid = "mspp_websiteid";
			public const string mspp_websiteidName = "mspp_websiteidname";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwnerIdName = "owneridname";
			public const string OwnerIdYomiName = "owneridyominame";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningBusinessUnitName = "owningbusinessunitname";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statecodeName = "statecodename";
			public const string statuscode = "statuscode";
			public const string statuscodeName = "statuscodename";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string adx_invitation_invitecontacts = "adx_invitation_invitecontacts";
			public const string adx_invitation_redeemedcontacts = "adx_invitation_redeemedcontacts";
			public const string adx_invitation_invitecontact = "adx_invitation_invitecontact";
			public const string adx_invitation_invitercontact = "adx_invitation_invitercontact";
			public const string adx_invitation_redeemedContact = "adx_invitation_redeemedContact";
		}
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public adx_invitation() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "adx_invitation";
	
	public const string EntityLogicalCollectionName = "adx_invitations";
	
	public const string EntitySetName = "adx_invitations";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// An account record to assign the redeemed contact to.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_assigntoaccount")]
	public Microsoft.Xrm.Sdk.EntityReference adx_assignToAccount
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("adx_assigntoaccount");
		}
		set
		{
			this.OnPropertyChanging("adx_assignToAccount");
			this.SetAttributeValue("adx_assigntoaccount", value);
			this.OnPropertyChanged("adx_assignToAccount");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_assigntoaccountname")]
	public string adx_assignToAccountName
	{
		get
		{
			if (this.FormattedValues.Contains("adx_assigntoaccount"))
			{
				return this.FormattedValues["adx_assigntoaccount"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_assigntoaccountyominame")]
	public string adx_assignToAccountYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("adx_assigntoaccount"))
			{
				return this.FormattedValues["adx_assigntoaccount"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// The date the invitation is no longer valid for redemption.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_expirydate")]
	public System.Nullable<System.DateTime> adx_expiryDate
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("adx_expirydate");
		}
		set
		{
			this.OnPropertyChanging("adx_expiryDate");
			this.SetAttributeValue("adx_expirydate", value);
			this.OnPropertyChanged("adx_expiryDate");
		}
	}
	
	/// <summary>
	/// Shows the user who is redeeming the invitation.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_invitationcode")]
	public string adx_invitationCode
	{
		get
		{
			return this.GetAttributeValue<string>("adx_invitationcode");
		}
		set
		{
			this.OnPropertyChanging("adx_invitationCode");
			this.SetAttributeValue("adx_invitationcode", value);
			this.OnPropertyChanged("adx_invitationCode");
		}
	}
	
	/// <summary>
	/// Shows the entity instance.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_invitationid")]
	public System.Nullable<System.Guid> adx_invitationId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("adx_invitationid");
		}
		set
		{
			this.OnPropertyChanging("adx_invitationId");
			this.SetAttributeValue("adx_invitationid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("adx_invitationId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_invitationid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.adx_invitationId = value;
		}
	}
	
	/// <summary>
	/// The contact to send an invitation to.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_invitecontact")]
	public Microsoft.Xrm.Sdk.EntityReference adx_inviteContact
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("adx_invitecontact");
		}
		set
		{
			this.OnPropertyChanging("adx_inviteContact");
			this.SetAttributeValue("adx_invitecontact", value);
			this.OnPropertyChanged("adx_inviteContact");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_invitecontactname")]
	public string adx_inviteContactName
	{
		get
		{
			if (this.FormattedValues.Contains("adx_invitecontact"))
			{
				return this.FormattedValues["adx_invitecontact"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_invitecontactyominame")]
	public string adx_inviteContactYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("adx_invitecontact"))
			{
				return this.FormattedValues["adx_invitecontact"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// The contact that invited.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_invitercontact")]
	public Microsoft.Xrm.Sdk.EntityReference adx_invitercontact
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("adx_invitercontact");
		}
		set
		{
			this.OnPropertyChanging("adx_invitercontact");
			this.SetAttributeValue("adx_invitercontact", value);
			this.OnPropertyChanged("adx_invitercontact");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_invitercontactname")]
	public string adx_invitercontactName
	{
		get
		{
			if (this.FormattedValues.Contains("adx_invitercontact"))
			{
				return this.FormattedValues["adx_invitercontact"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_invitercontactyominame")]
	public string adx_invitercontactYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("adx_invitercontact"))
			{
				return this.FormattedValues["adx_invitercontact"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_maximumredemptions")]
	public System.Nullable<int> adx_maximumRedemptions
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("adx_maximumredemptions");
		}
		set
		{
			this.OnPropertyChanging("adx_maximumRedemptions");
			this.SetAttributeValue("adx_maximumredemptions", value);
			this.OnPropertyChanged("adx_maximumRedemptions");
		}
	}
	
	/// <summary>
	/// Type the name of the custom entity.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_name")]
	public string adx_name
	{
		get
		{
			return this.GetAttributeValue<string>("adx_name");
		}
		set
		{
			this.OnPropertyChanging("adx_name");
			this.SetAttributeValue("adx_name", value);
			this.OnPropertyChanged("adx_name");
		}
	}
	
	/// <summary>
	/// The contact associated with the redemption of this invitation.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_redeemedcontact")]
	public Microsoft.Xrm.Sdk.EntityReference adx_redeemedContact
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("adx_redeemedcontact");
		}
		set
		{
			this.OnPropertyChanging("adx_redeemedContact");
			this.SetAttributeValue("adx_redeemedcontact", value);
			this.OnPropertyChanged("adx_redeemedContact");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_redeemedcontactname")]
	public string adx_redeemedContactName
	{
		get
		{
			if (this.FormattedValues.Contains("adx_redeemedcontact"))
			{
				return this.FormattedValues["adx_redeemedcontact"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_redeemedcontactyominame")]
	public string adx_redeemedContactYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("adx_redeemedcontact"))
			{
				return this.FormattedValues["adx_redeemedcontact"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// The current number of times this invitation has been redeemed.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_redemptions")]
	public System.Nullable<int> adx_redemptions
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("adx_redemptions");
		}
		set
		{
			this.OnPropertyChanging("adx_redemptions");
			this.SetAttributeValue("adx_redemptions", value);
			this.OnPropertyChanged("adx_redemptions");
		}
	}
	
	/// <summary>
	/// A workflow to execute on the redeeming contact.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_redemptionworkflow")]
	public Microsoft.Xrm.Sdk.EntityReference adx_redemptionWorkflow
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("adx_redemptionworkflow");
		}
		set
		{
			this.OnPropertyChanging("adx_redemptionWorkflow");
			this.SetAttributeValue("adx_redemptionworkflow", value);
			this.OnPropertyChanged("adx_redemptionWorkflow");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_redemptionworkflowname")]
	public string adx_redemptionWorkflowName
	{
		get
		{
			if (this.FormattedValues.Contains("adx_redemptionworkflow"))
			{
				return this.FormattedValues["adx_redemptionworkflow"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// The type of invitation.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_type")]
	public virtual adx_invitation_adx_type? adx_type
	{
		get
		{
			return ((adx_invitation_adx_type?)(EntityOptionSetEnum.GetEnum(this, "adx_type")));
		}
		set
		{
			this.OnPropertyChanging("adx_type");
			this.SetAttributeValue("adx_type", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("adx_type");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_typename")]
	public string adx_typeName
	{
		get
		{
			if (this.FormattedValues.Contains("adx_type"))
			{
				return this.FormattedValues["adx_type"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Shows who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
	public string CreatedByName
	{
		get
		{
			if (this.FormattedValues.Contains("createdby"))
			{
				return this.FormattedValues["createdby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
	public string CreatedByYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("createdby"))
			{
				return this.FormattedValues["createdby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Shows the date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Shows who created the record on behalf of another user.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
	public string CreatedOnBehalfByName
	{
		get
		{
			if (this.FormattedValues.Contains("createdonbehalfby"))
			{
				return this.FormattedValues["createdonbehalfby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
	public string CreatedOnBehalfByYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("createdonbehalfby"))
			{
				return this.FormattedValues["createdonbehalfby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Shows the sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// Shows who last updated the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
	public string ModifiedByName
	{
		get
		{
			if (this.FormattedValues.Contains("modifiedby"))
			{
				return this.FormattedValues["modifiedby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
	public string ModifiedByYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("modifiedby"))
			{
				return this.FormattedValues["modifiedby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Shows the date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Shows who last updated the record on behalf of another user.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
	public string ModifiedOnBehalfByName
	{
		get
		{
			if (this.FormattedValues.Contains("modifiedonbehalfby"))
			{
				return this.FormattedValues["modifiedonbehalfby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
	public string ModifiedOnBehalfByYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("modifiedonbehalfby"))
			{
				return this.FormattedValues["modifiedonbehalfby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mspp_websiteid")]
	public Microsoft.Xrm.Sdk.EntityReference mspp_websiteid
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("mspp_websiteid");
		}
		set
		{
			this.OnPropertyChanging("mspp_websiteid");
			this.SetAttributeValue("mspp_websiteid", value);
			this.OnPropertyChanged("mspp_websiteid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mspp_websiteidname")]
	public string mspp_websiteidName
	{
		get
		{
			if (this.FormattedValues.Contains("mspp_websiteid"))
			{
				return this.FormattedValues["mspp_websiteid"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Shows the date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// Enter the user who is assigned to manage the record. This field is updated every time the record is assigned to a different user.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// Name of the owner
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridname")]
	public string OwnerIdName
	{
		get
		{
			if (this.FormattedValues.Contains("ownerid"))
			{
				return this.FormattedValues["ownerid"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Yomi name of the owner
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridyominame")]
	public string OwnerIdYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("ownerid"))
			{
				return this.FormattedValues["ownerid"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Shows the business unit that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunitname")]
	public string OwningBusinessUnitName
	{
		get
		{
			if (this.FormattedValues.Contains("owningbusinessunit"))
			{
				return this.FormattedValues["owningbusinessunit"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Unique identifier for the team that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// Unique identifier for the user that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// Status of the Invitation
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual adx_invitation_statecode? statecode
	{
		get
		{
			return ((adx_invitation_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
	public string statecodeName
	{
		get
		{
			if (this.FormattedValues.Contains("statecode"))
			{
				return this.FormattedValues["statecode"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Select the invitation's status.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual adx_invitation_statuscode? statuscode
	{
		get
		{
			return ((adx_invitation_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
	public string statuscodeName
	{
		get
		{
			if (this.FormattedValues.Contains("statuscode"))
			{
				return this.FormattedValues["statuscode"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Shows the time zone code that was in use when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// N:N adx_invitation_invitecontacts
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_invitation_invitecontacts")]
	public System.Collections.Generic.IEnumerable<Contact> adx_invitation_invitecontacts
	{
		get
		{
			return this.GetRelatedEntities<Contact>("adx_invitation_invitecontacts", null);
		}
		set
		{
			this.OnPropertyChanging("adx_invitation_invitecontacts");
			this.SetRelatedEntities<Contact>("adx_invitation_invitecontacts", null, value);
			this.OnPropertyChanged("adx_invitation_invitecontacts");
		}
	}
	
	/// <summary>
	/// N:N adx_invitation_redeemedcontacts
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_invitation_redeemedcontacts")]
	public System.Collections.Generic.IEnumerable<Contact> adx_invitation_redeemedcontacts
	{
		get
		{
			return this.GetRelatedEntities<Contact>("adx_invitation_redeemedcontacts", null);
		}
		set
		{
			this.OnPropertyChanging("adx_invitation_redeemedcontacts");
			this.SetRelatedEntities<Contact>("adx_invitation_redeemedcontacts", null, value);
			this.OnPropertyChanged("adx_invitation_redeemedcontacts");
		}
	}
	
	/// <summary>
	/// N:1 adx_invitation_invitecontact
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_invitecontact")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_invitation_invitecontact")]
	public Contact adx_invitation_invitecontact
	{
		get
		{
			return this.GetRelatedEntity<Contact>("adx_invitation_invitecontact", null);
		}
		set
		{
			this.OnPropertyChanging("adx_invitation_invitecontact");
			this.SetRelatedEntity<Contact>("adx_invitation_invitecontact", null, value);
			this.OnPropertyChanged("adx_invitation_invitecontact");
		}
	}
	
	/// <summary>
	/// N:1 adx_invitation_invitercontact
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_invitercontact")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_invitation_invitercontact")]
	public Contact adx_invitation_invitercontact
	{
		get
		{
			return this.GetRelatedEntity<Contact>("adx_invitation_invitercontact", null);
		}
		set
		{
			this.OnPropertyChanging("adx_invitation_invitercontact");
			this.SetRelatedEntity<Contact>("adx_invitation_invitercontact", null, value);
			this.OnPropertyChanged("adx_invitation_invitercontact");
		}
	}
	
	/// <summary>
	/// N:1 adx_invitation_redeemedContact
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_redeemedcontact")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_invitation_redeemedContact")]
	public Contact adx_invitation_redeemedContact
	{
		get
		{
			return this.GetRelatedEntity<Contact>("adx_invitation_redeemedContact", null);
		}
		set
		{
			this.OnPropertyChanging("adx_invitation_redeemedContact");
			this.SetRelatedEntity<Contact>("adx_invitation_redeemedContact", null, value);
			this.OnPropertyChanged("adx_invitation_redeemedContact");
		}
	}
}
#pragma warning restore CS1591
