#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Delivery route. Codes: Email=100000000, ManualCode=100000001, AssignmentNotification=100000002.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum mp_onboardingrequest_mp_invitationdeliverymode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Email = 100000000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	ManualCode = 100000001,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	AssignmentNotification = 100000002,
}

/// <summary>
/// Invitation lifecycle. Codes: Pending=100000000, ManualDeliveryRequired=100000001, EmailSent=100000002, Redeemed=100000003, Expired=100000004, Replaced=100000005.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum mp_onboardingrequest_mp_invitationstatus
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Pending = 100000000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	ManualDeliveryRequired = 100000001,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	EmailSent = 100000002,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Redeemed = 100000003,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Expired = 100000004,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Replaced = 100000005,
}

/// <summary>
/// Target user classification. Codes: NewUser=100000000, ExistingUser=100000001, Unresolved=100000002.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum mp_onboardingrequest_mp_requesttype
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	NewUser = 100000000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	ExistingUser = 100000001,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Unresolved = 100000002,
}

/// <summary>
/// Processing status. Codes: Pending=100000000, Processing=100000001, Completed=100000002, Failed=100000003, Cancelled=100000004, NeedsReview=100000005.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum mp_onboardingrequest_mp_status
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Pending = 100000000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Processing = 100000001,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Completed = 100000002,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Failed = 100000003,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Cancelled = 100000004,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	NeedsReview = 100000005,
}

/// <summary>
/// Status of the OnboardingRequests
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum mp_onboardingrequest_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Reason for the status of the OnboardingRequests
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum mp_onboardingrequest_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 2,
}

/// <summary>
/// Durable request queue row created by the portal and processed by Dataverse-triggered automation.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("mp_onboardingrequest")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class mp_OnboardingRequest : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
				/// <summary>
		/// Available fields, a the time of codegen, for the mp_onboardingrequest entity
		/// </summary>
		public partial class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedByYomiName = "createdbyyominame";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedByYomiName = "modifiedbyyominame";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string mp_ActorEmail = "mp_actoremail";
			public const string mp_ActorRolesJson = "mp_actorrolesjson";
			public const string mp_AuditKey = "mp_auditkey";
			public const string mp_CompletedAt = "mp_completedat";
			public const string mp_ContactId = "mp_contactid";
			public const string mp_Email = "mp_email";
			public const string mp_ErrorCategory = "mp_errorcategory";
			public const string mp_ErrorJson = "mp_errorjson";
			public const string mp_FormScopeJson = "mp_formscopejson";
			public const string mp_FullName = "mp_fullname";
			public const string mp_InvitationCode = "mp_invitationcode";
			public const string mp_InvitationDeliveryMode = "mp_invitationdeliverymode";
			public const string mp_invitationdeliverymodeName = "mp_invitationdeliverymodename";
			public const string mp_InvitationExpiresAt = "mp_invitationexpiresat";
			public const string mp_InvitationId = "mp_invitationid";
			public const string mp_InvitationRedeemUrl = "mp_invitationredeemurl";
			public const string mp_InvitationStatus = "mp_invitationstatus";
			public const string mp_invitationstatusName = "mp_invitationstatusname";
			public const string mp_LastAttemptAt = "mp_lastattemptat";
			public const string mp_OnboardingRequestId = "mp_onboardingrequestid";
			public const string Id = "mp_onboardingrequestid";
			public const string mp_ProcessingAttempts = "mp_processingattempts";
			public const string mp_ProjectId = "mp_projectid";
			public const string mp_ProjectName = "mp_projectname";
			public const string mp_Reason = "mp_reason";
			public const string mp_ReplacementOfRequestId = "mp_replacementofrequestid";
			public const string mp_RequestId = "mp_requestid";
			public const string mp_RequestKey = "mp_requestkey";
			public const string mp_RequestType = "mp_requesttype";
			public const string mp_requesttypeName = "mp_requesttypename";
			public const string mp_ResultMessage = "mp_resultmessage";
			public const string mp_SourceRoute = "mp_sourceroute";
			public const string mp_Status = "mp_status";
			public const string mp_statusName = "mp_statusname";
			public const string mp_TargetRole = "mp_targetrole";
			public const string OrganizationId = "organizationid";
			public const string OrganizationIdName = "organizationidname";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string statecode = "statecode";
			public const string statecodeName = "statecodename";
			public const string statuscode = "statuscode";
			public const string statuscodeName = "statuscodename";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
		}
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public mp_OnboardingRequest() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "mp_onboardingrequest";
	
	public const string EntityLogicalCollectionName = "mp_onboardingrequests";
	
	public const string EntitySetName = "mp_onboardingrequests";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
	public string CreatedByName
	{
		get
		{
			if (this.FormattedValues.Contains("createdby"))
			{
				return this.FormattedValues["createdby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
	public string CreatedByYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("createdby"))
			{
				return this.FormattedValues["createdby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
	public string CreatedOnBehalfByName
	{
		get
		{
			if (this.FormattedValues.Contains("createdonbehalfby"))
			{
				return this.FormattedValues["createdonbehalfby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
	public string CreatedOnBehalfByYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("createdonbehalfby"))
			{
				return this.FormattedValues["createdonbehalfby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
	public string ModifiedByName
	{
		get
		{
			if (this.FormattedValues.Contains("modifiedby"))
			{
				return this.FormattedValues["modifiedby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
	public string ModifiedByYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("modifiedby"))
			{
				return this.FormattedValues["modifiedby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
	public string ModifiedOnBehalfByName
	{
		get
		{
			if (this.FormattedValues.Contains("modifiedonbehalfby"))
			{
				return this.FormattedValues["modifiedonbehalfby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
	public string ModifiedOnBehalfByYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("modifiedonbehalfby"))
			{
				return this.FormattedValues["modifiedonbehalfby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Signed-in administrator email.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_actoremail")]
	public string mp_ActorEmail
	{
		get
		{
			return this.GetAttributeValue<string>("mp_actoremail");
		}
		set
		{
			this.OnPropertyChanging("mp_ActorEmail");
			this.SetAttributeValue("mp_actoremail", value);
			this.OnPropertyChanged("mp_ActorEmail");
		}
	}
	
	/// <summary>
	/// Detected administrator web-role snapshot.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_actorrolesjson")]
	public string mp_ActorRolesJson
	{
		get
		{
			return this.GetAttributeValue<string>("mp_actorrolesjson");
		}
		set
		{
			this.OnPropertyChanging("mp_ActorRolesJson");
			this.SetAttributeValue("mp_actorrolesjson", value);
			this.OnPropertyChanged("mp_ActorRolesJson");
		}
	}
	
	/// <summary>
	/// Access audit event key written by automation after audit create succeeds.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_auditkey")]
	public string mp_AuditKey
	{
		get
		{
			return this.GetAttributeValue<string>("mp_auditkey");
		}
		set
		{
			this.OnPropertyChanging("mp_AuditKey");
			this.SetAttributeValue("mp_auditkey", value);
			this.OnPropertyChanged("mp_AuditKey");
		}
	}
	
	/// <summary>
	/// Completion timestamp when status is Completed.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_completedat")]
	public System.Nullable<System.DateTime> mp_CompletedAt
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("mp_completedat");
		}
		set
		{
			this.OnPropertyChanging("mp_CompletedAt");
			this.SetAttributeValue("mp_completedat", value);
			this.OnPropertyChanged("mp_CompletedAt");
		}
	}
	
	/// <summary>
	/// Resolved Power Pages contact id written by automation.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_contactid")]
	public string mp_ContactId
	{
		get
		{
			return this.GetAttributeValue<string>("mp_contactid");
		}
		set
		{
			this.OnPropertyChanging("mp_ContactId");
			this.SetAttributeValue("mp_contactid", value);
			this.OnPropertyChanged("mp_ContactId");
		}
	}
	
	/// <summary>
	/// Normalized primary email used for contact lookup and assignment matching.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_email")]
	public string mp_Email
	{
		get
		{
			return this.GetAttributeValue<string>("mp_email");
		}
		set
		{
			this.OnPropertyChanging("mp_Email");
			this.SetAttributeValue("mp_email", value);
			this.OnPropertyChanged("mp_Email");
		}
	}
	
	/// <summary>
	/// Sanitized category for failure handling.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_errorcategory")]
	public string mp_ErrorCategory
	{
		get
		{
			return this.GetAttributeValue<string>("mp_errorcategory");
		}
		set
		{
			this.OnPropertyChanging("mp_ErrorCategory");
			this.SetAttributeValue("mp_errorcategory", value);
			this.OnPropertyChanged("mp_ErrorCategory");
		}
	}
	
	/// <summary>
	/// Sanitized structured error. Must not include secrets or raw invitation URLs.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_errorjson")]
	public string mp_ErrorJson
	{
		get
		{
			return this.GetAttributeValue<string>("mp_errorjson");
		}
		set
		{
			this.OnPropertyChanging("mp_ErrorJson");
			this.SetAttributeValue("mp_errorjson", value);
			this.OnPropertyChanged("mp_ErrorJson");
		}
	}
	
	/// <summary>
	/// JSON array of selected form and form-version identifiers.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_formscopejson")]
	public string mp_FormScopeJson
	{
		get
		{
			return this.GetAttributeValue<string>("mp_formscopejson");
		}
		set
		{
			this.OnPropertyChanging("mp_FormScopeJson");
			this.SetAttributeValue("mp_formscopejson", value);
			this.OnPropertyChanged("mp_FormScopeJson");
		}
	}
	
	/// <summary>
	/// Requested user full name.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_fullname")]
	public string mp_FullName
	{
		get
		{
			return this.GetAttributeValue<string>("mp_fullname");
		}
		set
		{
			this.OnPropertyChanging("mp_FullName");
			this.SetAttributeValue("mp_fullname", value);
			this.OnPropertyChanged("mp_FullName");
		}
	}
	
	/// <summary>
	/// Invitation code for approved manual/verbal fallback. Expose only to Platform Administrator request readers.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_invitationcode")]
	public string mp_InvitationCode
	{
		get
		{
			return this.GetAttributeValue<string>("mp_invitationcode");
		}
		set
		{
			this.OnPropertyChanging("mp_InvitationCode");
			this.SetAttributeValue("mp_invitationcode", value);
			this.OnPropertyChanged("mp_InvitationCode");
		}
	}
	
	/// <summary>
	/// Delivery route. Codes: Email=100000000, ManualCode=100000001, AssignmentNotification=100000002.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_invitationdeliverymode")]
	public virtual mp_onboardingrequest_mp_invitationdeliverymode? mp_InvitationDeliveryMode
	{
		get
		{
			return ((mp_onboardingrequest_mp_invitationdeliverymode?)(EntityOptionSetEnum.GetEnum(this, "mp_invitationdeliverymode")));
		}
		set
		{
			this.OnPropertyChanging("mp_InvitationDeliveryMode");
			this.SetAttributeValue("mp_invitationdeliverymode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("mp_InvitationDeliveryMode");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_invitationdeliverymodename")]
	public string mp_invitationdeliverymodeName
	{
		get
		{
			if (this.FormattedValues.Contains("mp_invitationdeliverymode"))
			{
				return this.FormattedValues["mp_invitationdeliverymode"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Invitation expiry timestamp used to decide whether a replacement invitation is required.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_invitationexpiresat")]
	public System.Nullable<System.DateTime> mp_InvitationExpiresAt
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("mp_invitationexpiresat");
		}
		set
		{
			this.OnPropertyChanging("mp_InvitationExpiresAt");
			this.SetAttributeValue("mp_invitationexpiresat", value);
			this.OnPropertyChanged("mp_InvitationExpiresAt");
		}
	}
	
	/// <summary>
	/// Power Pages invitation id written by automation when a new-user invitation is created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_invitationid")]
	public string mp_InvitationId
	{
		get
		{
			return this.GetAttributeValue<string>("mp_invitationid");
		}
		set
		{
			this.OnPropertyChanging("mp_InvitationId");
			this.SetAttributeValue("mp_invitationid", value);
			this.OnPropertyChanged("mp_InvitationId");
		}
	}
	
	/// <summary>
	/// Portal invitation redemption URL without credentials or bearer tokens.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_invitationredeemurl")]
	public string mp_InvitationRedeemUrl
	{
		get
		{
			return this.GetAttributeValue<string>("mp_invitationredeemurl");
		}
		set
		{
			this.OnPropertyChanging("mp_InvitationRedeemUrl");
			this.SetAttributeValue("mp_invitationredeemurl", value);
			this.OnPropertyChanged("mp_InvitationRedeemUrl");
		}
	}
	
	/// <summary>
	/// Invitation lifecycle. Codes: Pending=100000000, ManualDeliveryRequired=100000001, EmailSent=100000002, Redeemed=100000003, Expired=100000004, Replaced=100000005.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_invitationstatus")]
	public virtual mp_onboardingrequest_mp_invitationstatus? mp_InvitationStatus
	{
		get
		{
			return ((mp_onboardingrequest_mp_invitationstatus?)(EntityOptionSetEnum.GetEnum(this, "mp_invitationstatus")));
		}
		set
		{
			this.OnPropertyChanging("mp_InvitationStatus");
			this.SetAttributeValue("mp_invitationstatus", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("mp_InvitationStatus");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_invitationstatusname")]
	public string mp_invitationstatusName
	{
		get
		{
			if (this.FormattedValues.Contains("mp_invitationstatus"))
			{
				return this.FormattedValues["mp_invitationstatus"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Last server-side processing attempt timestamp.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_lastattemptat")]
	public System.Nullable<System.DateTime> mp_LastAttemptAt
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("mp_lastattemptat");
		}
		set
		{
			this.OnPropertyChanging("mp_LastAttemptAt");
			this.SetAttributeValue("mp_lastattemptat", value);
			this.OnPropertyChanged("mp_LastAttemptAt");
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_onboardingrequestid")]
	public System.Nullable<System.Guid> mp_OnboardingRequestId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("mp_onboardingrequestid");
		}
		set
		{
			this.OnPropertyChanging("mp_OnboardingRequestId");
			this.SetAttributeValue("mp_onboardingrequestid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("mp_OnboardingRequestId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_onboardingrequestid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.mp_OnboardingRequestId = value;
		}
	}
	
	/// <summary>
	/// Number of server-side processing attempts. Defaults to 0.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_processingattempts")]
	public System.Nullable<int> mp_ProcessingAttempts
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("mp_processingattempts");
		}
		set
		{
			this.OnPropertyChanging("mp_ProcessingAttempts");
			this.SetAttributeValue("mp_processingattempts", value);
			this.OnPropertyChanged("mp_ProcessingAttempts");
		}
	}
	
	/// <summary>
	/// Project identifier snapshot. Lookup can replace this after the platform project schema is finalized.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_projectid")]
	public string mp_ProjectId
	{
		get
		{
			return this.GetAttributeValue<string>("mp_projectid");
		}
		set
		{
			this.OnPropertyChanging("mp_ProjectId");
			this.SetAttributeValue("mp_projectid", value);
			this.OnPropertyChanged("mp_ProjectId");
		}
	}
	
	/// <summary>
	/// Project display-name snapshot for operator readability.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_projectname")]
	public string mp_ProjectName
	{
		get
		{
			return this.GetAttributeValue<string>("mp_projectname");
		}
		set
		{
			this.OnPropertyChanging("mp_ProjectName");
			this.SetAttributeValue("mp_projectname", value);
			this.OnPropertyChanged("mp_ProjectName");
		}
	}
	
	/// <summary>
	/// Business reason entered by the administrator.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_reason")]
	public string mp_Reason
	{
		get
		{
			return this.GetAttributeValue<string>("mp_reason");
		}
		set
		{
			this.OnPropertyChanging("mp_Reason");
			this.SetAttributeValue("mp_reason", value);
			this.OnPropertyChanged("mp_Reason");
		}
	}
	
	/// <summary>
	/// Original request id when an administrator creates a replacement invitation after expiry or loss.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_replacementofrequestid")]
	public string mp_ReplacementOfRequestId
	{
		get
		{
			return this.GetAttributeValue<string>("mp_replacementofrequestid");
		}
		set
		{
			this.OnPropertyChanging("mp_ReplacementOfRequestId");
			this.SetAttributeValue("mp_replacementofrequestid", value);
			this.OnPropertyChanged("mp_ReplacementOfRequestId");
		}
	}
	
	/// <summary>
	/// User-facing request id shown in the portal result panel.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_requestid")]
	public string mp_RequestId
	{
		get
		{
			return this.GetAttributeValue<string>("mp_requestid");
		}
		set
		{
			this.OnPropertyChanging("mp_RequestId");
			this.SetAttributeValue("mp_requestid", value);
			this.OnPropertyChanged("mp_RequestId");
		}
	}
	
	/// <summary>
	/// Stable idempotency key generated by the portal.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_requestkey")]
	public string mp_RequestKey
	{
		get
		{
			return this.GetAttributeValue<string>("mp_requestkey");
		}
		set
		{
			this.OnPropertyChanging("mp_RequestKey");
			this.SetAttributeValue("mp_requestkey", value);
			this.OnPropertyChanged("mp_RequestKey");
		}
	}
	
	/// <summary>
	/// Target user classification. Codes: NewUser=100000000, ExistingUser=100000001, Unresolved=100000002.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_requesttype")]
	public virtual mp_onboardingrequest_mp_requesttype? mp_RequestType
	{
		get
		{
			return ((mp_onboardingrequest_mp_requesttype?)(EntityOptionSetEnum.GetEnum(this, "mp_requesttype")));
		}
		set
		{
			this.OnPropertyChanging("mp_RequestType");
			this.SetAttributeValue("mp_requesttype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("mp_RequestType");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_requesttypename")]
	public string mp_requesttypeName
	{
		get
		{
			if (this.FormattedValues.Contains("mp_requesttype"))
			{
				return this.FormattedValues["mp_requesttype"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Business-readable status or failure message.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_resultmessage")]
	public string mp_ResultMessage
	{
		get
		{
			return this.GetAttributeValue<string>("mp_resultmessage");
		}
		set
		{
			this.OnPropertyChanging("mp_ResultMessage");
			this.SetAttributeValue("mp_resultmessage", value);
			this.OnPropertyChanged("mp_ResultMessage");
		}
	}
	
	/// <summary>
	/// Portal route/action source, for example UserAccess:AddUser.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_sourceroute")]
	public string mp_SourceRoute
	{
		get
		{
			return this.GetAttributeValue<string>("mp_sourceroute");
		}
		set
		{
			this.OnPropertyChanging("mp_SourceRoute");
			this.SetAttributeValue("mp_sourceroute", value);
			this.OnPropertyChanged("mp_SourceRoute");
		}
	}
	
	/// <summary>
	/// Processing status. Codes: Pending=100000000, Processing=100000001, Completed=100000002, Failed=100000003, Cancelled=100000004, NeedsReview=100000005.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_status")]
	public virtual mp_onboardingrequest_mp_status? mp_Status
	{
		get
		{
			return ((mp_onboardingrequest_mp_status?)(EntityOptionSetEnum.GetEnum(this, "mp_status")));
		}
		set
		{
			this.OnPropertyChanging("mp_Status");
			this.SetAttributeValue("mp_status", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("mp_Status");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_statusname")]
	public string mp_statusName
	{
		get
		{
			if (this.FormattedValues.Contains("mp_status"))
			{
				return this.FormattedValues["mp_status"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Requested TACATDP role label.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mp_targetrole")]
	public string mp_TargetRole
	{
		get
		{
			return this.GetAttributeValue<string>("mp_targetrole");
		}
		set
		{
			this.OnPropertyChanging("mp_TargetRole");
			this.SetAttributeValue("mp_targetrole", value);
			this.OnPropertyChanged("mp_TargetRole");
		}
	}
	
	/// <summary>
	/// Unique identifier for the organization
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
	public Microsoft.Xrm.Sdk.EntityReference OrganizationId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationidname")]
	public string OrganizationIdName
	{
		get
		{
			if (this.FormattedValues.Contains("organizationid"))
			{
				return this.FormattedValues["organizationid"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// Status of the OnboardingRequests
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual mp_onboardingrequest_statecode? statecode
	{
		get
		{
			return ((mp_onboardingrequest_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
	public string statecodeName
	{
		get
		{
			if (this.FormattedValues.Contains("statecode"))
			{
				return this.FormattedValues["statecode"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Reason for the status of the OnboardingRequests
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual mp_onboardingrequest_statuscode? statuscode
	{
		get
		{
			return ((mp_onboardingrequest_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
	public string statuscodeName
	{
		get
		{
			if (this.FormattedValues.Contains("statuscode"))
			{
				return this.FormattedValues["statuscode"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Time zone code that was in use when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
}
#pragma warning restore CS1591
