#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// The run mode used by the desktop flow run
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum flowsession_runmode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Local = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Attended = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Unattended = 2,
}

/// <summary>
/// The run session mode used by the desktop flow run.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum flowsession_runsessionmode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Unapplicable = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Default = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	PictureInPicture = 2,
}

/// <summary>
/// Status of the Flow Session
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum flowsession_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Reason for the status of the Flow Session
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum flowsession_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	NotSpecified = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Paused = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Running = 2,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Waiting = 3,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Succeeded = 4,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Skipped = 5,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Suspended = 6,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Cancelled = 7,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Failed = 8,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Faulted = 9,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	TimedOut = 10,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Aborted = 11,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Ignored = 12,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Deleted = 13,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Terminated = 14,
}

[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum flowsession_subcategory
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Default = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Test = 1,
}

/// <summary>
/// The type of trigger used to run the desktop flow.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum flowsession_triggertype
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	ApiFlow = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	DesktopFlow = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Local = 2,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	RunDesktopFlowDataverseApi = 3,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Cua = 4,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Trigger = 5,
}

/// <summary>
/// Entity to store the information that is generated when a Power Automate Desktop flow runs.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("flowsession")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class flowsession : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
				/// <summary>
		/// Available fields, a the time of codegen, for the flowsession entity
		/// </summary>
		public partial class Fields
		{
			public const string AdditionalContext = "additionalcontext";
			public const string AdditionalContext_Name = "additionalcontext_name";
			public const string CallbackUrl = "callbackurl";
			public const string ClientTrackingId = "clienttrackingid";
			public const string CompletedOn = "completedon";
			public const string ComputerUseAgentId = "computeruseagentid";
			public const string ComputerUseAgentIdName = "computeruseagentidname";
			public const string ConnectionId = "connectionid";
			public const string Context = "context";
			public const string CorrelationId = "correlationid";
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedByYomiName = "createdbyyominame";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string Credentials = "credentials";
			public const string ErrorCode = "errorcode";
			public const string ErrorDetails = "errordetails";
			public const string ErrorInnerError = "errorinnererror";
			public const string ErrorMessage = "errormessage";
			public const string flowsessionId = "flowsessionid";
			public const string Id = "flowsessionid";
			public const string flowtestsessionid = "flowtestsessionid";
			public const string flowtestsessionidName = "flowtestsessionidname";
			public const string flowtriggerid = "flowtriggerid";
			public const string flowtriggeridName = "flowtriggeridname";
			public const string Gateway = "gateway";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string Inputs = "inputs";
			public const string Inputs_Name = "inputs_name";
			public const string MachineGroupId = "machinegroupid";
			public const string MachineGroupIdName = "machinegroupidname";
			public const string MachineId = "machineid";
			public const string MachineIdName = "machineidname";
			public const string MachinePercentCpuUsage = "machinepercentcpuusage";
			public const string MachinePercentRamUsage = "machinepercentramusage";
			public const string MachineRamUsage = "machineramusage";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedByYomiName = "modifiedbyyominame";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string Name = "name";
			public const string Outputs = "outputs";
			public const string Outputs_Name = "outputs_name";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwnerIdName = "owneridname";
			public const string OwnerIdYomiName = "owneridyominame";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningBusinessUnitName = "owningbusinessunitname";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string ParentCloudFlowRunSequenceId = "parentcloudflowrunsequenceid";
			public const string ParentDesktopFlowRunGuid = "parentdesktopflowrunguid";
			public const string ParentDesktopFlowRunId = "parentdesktopflowrunid";
			public const string parentdesktopflowrunidName = "parentdesktopflowrunidname";
			public const string ParentWorkflowId = "parentworkflowid";
			public const string ProcessVersion = "processversion";
			public const string RegardingObjectId = "regardingobjectid";
			public const string RegardingObjectIdName = "regardingobjectidname";
			public const string RegardingObjectIdYomiName = "regardingobjectidyominame";
			public const string RunDetails = "rundetails";
			public const string RunDuration = "runduration";
			public const string RunExecutionDuration = "runexecutionduration";
			public const string RunMode = "runmode";
			public const string runmodeName = "runmodename";
			public const string RunSessionMode = "runsessionmode";
			public const string runsessionmodeName = "runsessionmodename";
			public const string RunWaitDuration = "runwaitduration";
			public const string SessionUsername = "sessionusername";
			public const string SessionUserSID = "sessionusersid";
			public const string StartedOn = "startedon";
			public const string statecode = "statecode";
			public const string statecodeName = "statecodename";
			public const string statuscode = "statuscode";
			public const string statuscodeName = "statuscodename";
			public const string SubCategory = "subcategory";
			public const string subcategoryName = "subcategoryname";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string TriggerType = "triggertype";
			public const string triggertypeName = "triggertypename";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string Referencedflowsession_flowsession_parentdesktopflowrunid = "Referencedflowsession_flowsession_parentdesktopflowrunid";
			public const string Referencingflowsession_flowsession_parentdesktopflowrunid = "flowsession_flowsession_parentdesktopflowrunid";
		}
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public flowsession() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "flowsession";
	
	public const string EntityLogicalCollectionName = "flowsessions";
	
	public const string EntitySetName = "flowsessions";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// Additional context about flow session.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("additionalcontext")]
	public System.Nullable<System.Guid> AdditionalContext
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("additionalcontext");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("additionalcontext_name")]
	public string AdditionalContext_Name
	{
		get
		{
			return this.GetAttributeValue<string>("additionalcontext_name");
		}
	}
	
	/// <summary>
	/// URL that will be called once the flow session is complete.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("callbackurl")]
	public string CallbackUrl
	{
		get
		{
			return this.GetAttributeValue<string>("callbackurl");
		}
		set
		{
			this.OnPropertyChanging("CallbackUrl");
			this.SetAttributeValue("callbackurl", value);
			this.OnPropertyChanged("CallbackUrl");
		}
	}
	
	/// <summary>
	/// The client tracking id of the run
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("clienttrackingid")]
	public string ClientTrackingId
	{
		get
		{
			return this.GetAttributeValue<string>("clienttrackingid");
		}
		set
		{
			this.OnPropertyChanging("ClientTrackingId");
			this.SetAttributeValue("clienttrackingid", value);
			this.OnPropertyChanged("ClientTrackingId");
		}
	}
	
	/// <summary>
	/// The date and time at which the flow session was completed.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("completedon")]
	public System.Nullable<System.DateTime> CompletedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("completedon");
		}
		set
		{
			this.OnPropertyChanging("CompletedOn");
			this.SetAttributeValue("completedon", value);
			this.OnPropertyChanged("CompletedOn");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("computeruseagentid")]
	public Microsoft.Xrm.Sdk.EntityReference ComputerUseAgentId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("computeruseagentid");
		}
		set
		{
			this.OnPropertyChanging("ComputerUseAgentId");
			this.SetAttributeValue("computeruseagentid", value);
			this.OnPropertyChanged("ComputerUseAgentId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("computeruseagentidname")]
	public string ComputerUseAgentIdName
	{
		get
		{
			if (this.FormattedValues.Contains("computeruseagentid"))
			{
				return this.FormattedValues["computeruseagentid"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// The id of the connection used in the Desktop Flow run.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("connectionid")]
	public string ConnectionId
	{
		get
		{
			return this.GetAttributeValue<string>("connectionid");
		}
		set
		{
			this.OnPropertyChanging("ConnectionId");
			this.SetAttributeValue("connectionid", value);
			this.OnPropertyChanged("ConnectionId");
		}
	}
	
	/// <summary>
	/// Context about flow session.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("context")]
	public string Context
	{
		get
		{
			return this.GetAttributeValue<string>("context");
		}
		set
		{
			this.OnPropertyChanging("Context");
			this.SetAttributeValue("context", value);
			this.OnPropertyChanged("Context");
		}
	}
	
	/// <summary>
	/// Unique identifier used to correlate between multiple SDK requests and flow executions.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("correlationid")]
	public string CorrelationId
	{
		get
		{
			return this.GetAttributeValue<string>("correlationid");
		}
		set
		{
			this.OnPropertyChanging("CorrelationId");
			this.SetAttributeValue("correlationid", value);
			this.OnPropertyChanged("CorrelationId");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
	public string CreatedByName
	{
		get
		{
			if (this.FormattedValues.Contains("createdby"))
			{
				return this.FormattedValues["createdby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
	public string CreatedByYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("createdby"))
			{
				return this.FormattedValues["createdby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
	public string CreatedOnBehalfByName
	{
		get
		{
			if (this.FormattedValues.Contains("createdonbehalfby"))
			{
				return this.FormattedValues["createdonbehalfby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
	public string CreatedOnBehalfByYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("createdonbehalfby"))
			{
				return this.FormattedValues["createdonbehalfby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Credentials related to this run.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("credentials")]
	public string Credentials
	{
		get
		{
			return this.GetAttributeValue<string>("credentials");
		}
		set
		{
			this.OnPropertyChanging("Credentials");
			this.SetAttributeValue("credentials", value);
			this.OnPropertyChanged("Credentials");
		}
	}
	
	/// <summary>
	/// Error code describing the failure in flow session execution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("errorcode")]
	public string ErrorCode
	{
		get
		{
			return this.GetAttributeValue<string>("errorcode");
		}
		set
		{
			this.OnPropertyChanging("ErrorCode");
			this.SetAttributeValue("errorcode", value);
			this.OnPropertyChanged("ErrorCode");
		}
	}
	
	/// <summary>
	/// Details of the failure in flow session execution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("errordetails")]
	public string ErrorDetails
	{
		get
		{
			return this.GetAttributeValue<string>("errordetails");
		}
		set
		{
			this.OnPropertyChanging("ErrorDetails");
			this.SetAttributeValue("errordetails", value);
			this.OnPropertyChanged("ErrorDetails");
		}
	}
	
	/// <summary>
	/// Specific information about the failure in flow session execution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("errorinnererror")]
	public string ErrorInnerError
	{
		get
		{
			return this.GetAttributeValue<string>("errorinnererror");
		}
		set
		{
			this.OnPropertyChanging("ErrorInnerError");
			this.SetAttributeValue("errorinnererror", value);
			this.OnPropertyChanged("ErrorInnerError");
		}
	}
	
	/// <summary>
	/// Message describing the failure in flow session execution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("errormessage")]
	public string ErrorMessage
	{
		get
		{
			return this.GetAttributeValue<string>("errormessage");
		}
		set
		{
			this.OnPropertyChanging("ErrorMessage");
			this.SetAttributeValue("errormessage", value);
			this.OnPropertyChanged("ErrorMessage");
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("flowsessionid")]
	public System.Nullable<System.Guid> flowsessionId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("flowsessionid");
		}
		set
		{
			this.OnPropertyChanging("flowsessionId");
			this.SetAttributeValue("flowsessionid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("flowsessionId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("flowsessionid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.flowsessionId = value;
		}
	}
	
	/// <summary>
	/// Unique identifier of the flow test session with which the flow session is associated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("flowtestsessionid")]
	public Microsoft.Xrm.Sdk.EntityReference flowtestsessionid
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("flowtestsessionid");
		}
		set
		{
			this.OnPropertyChanging("flowtestsessionid");
			this.SetAttributeValue("flowtestsessionid", value);
			this.OnPropertyChanged("flowtestsessionid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("flowtestsessionidname")]
	public string flowtestsessionidName
	{
		get
		{
			if (this.FormattedValues.Contains("flowtestsessionid"))
			{
				return this.FormattedValues["flowtestsessionid"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("flowtriggerid")]
	public Microsoft.Xrm.Sdk.EntityReference flowtriggerid
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("flowtriggerid");
		}
		set
		{
			this.OnPropertyChanging("flowtriggerid");
			this.SetAttributeValue("flowtriggerid", value);
			this.OnPropertyChanged("flowtriggerid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("flowtriggeridname")]
	public string flowtriggeridName
	{
		get
		{
			if (this.FormattedValues.Contains("flowtriggerid"))
			{
				return this.FormattedValues["flowtriggerid"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// The name of the gateway used.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("gateway")]
	public string Gateway
	{
		get
		{
			return this.GetAttributeValue<string>("gateway");
		}
		set
		{
			this.OnPropertyChanging("Gateway");
			this.SetAttributeValue("gateway", value);
			this.OnPropertyChanged("Gateway");
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// Inputs provided for the flow session execution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("inputs")]
	public System.Nullable<System.Guid> Inputs
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("inputs");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("inputs_name")]
	public string Inputs_Name
	{
		get
		{
			return this.GetAttributeValue<string>("inputs_name");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("machinegroupid")]
	public Microsoft.Xrm.Sdk.EntityReference MachineGroupId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("machinegroupid");
		}
		set
		{
			this.OnPropertyChanging("MachineGroupId");
			this.SetAttributeValue("machinegroupid", value);
			this.OnPropertyChanged("MachineGroupId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("machinegroupidname")]
	public string MachineGroupIdName
	{
		get
		{
			if (this.FormattedValues.Contains("machinegroupid"))
			{
				return this.FormattedValues["machinegroupid"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("machineid")]
	public Microsoft.Xrm.Sdk.EntityReference MachineId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("machineid");
		}
		set
		{
			this.OnPropertyChanging("MachineId");
			this.SetAttributeValue("machineid", value);
			this.OnPropertyChanged("MachineId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("machineidname")]
	public string MachineIdName
	{
		get
		{
			if (this.FormattedValues.Contains("machineid"))
			{
				return this.FormattedValues["machineid"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// The percentage of CPU utilization by the machine
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("machinepercentcpuusage")]
	public System.Nullable<double> MachinePercentCpuUsage
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<double>>("machinepercentcpuusage");
		}
		set
		{
			this.OnPropertyChanging("MachinePercentCpuUsage");
			this.SetAttributeValue("machinepercentcpuusage", value);
			this.OnPropertyChanged("MachinePercentCpuUsage");
		}
	}
	
	/// <summary>
	/// The percentage of RAM utilization by the machine
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("machinepercentramusage")]
	public System.Nullable<double> MachinePercentRamUsage
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<double>>("machinepercentramusage");
		}
		set
		{
			this.OnPropertyChanging("MachinePercentRamUsage");
			this.SetAttributeValue("machinepercentramusage", value);
			this.OnPropertyChanged("MachinePercentRamUsage");
		}
	}
	
	/// <summary>
	/// The machine RAM usage in Mo
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("machineramusage")]
	public System.Nullable<int> MachineRamUsage
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("machineramusage");
		}
		set
		{
			this.OnPropertyChanging("MachineRamUsage");
			this.SetAttributeValue("machineramusage", value);
			this.OnPropertyChanged("MachineRamUsage");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
	public string ModifiedByName
	{
		get
		{
			if (this.FormattedValues.Contains("modifiedby"))
			{
				return this.FormattedValues["modifiedby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
	public string ModifiedByYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("modifiedby"))
			{
				return this.FormattedValues["modifiedby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
	public string ModifiedOnBehalfByName
	{
		get
		{
			if (this.FormattedValues.Contains("modifiedonbehalfby"))
			{
				return this.FormattedValues["modifiedonbehalfby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
	public string ModifiedOnBehalfByYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("modifiedonbehalfby"))
			{
				return this.FormattedValues["modifiedonbehalfby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// The name of the custom entity.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
	public string Name
	{
		get
		{
			return this.GetAttributeValue<string>("name");
		}
		set
		{
			this.OnPropertyChanging("Name");
			this.SetAttributeValue("name", value);
			this.OnPropertyChanged("Name");
		}
	}
	
	/// <summary>
	/// Outputs generated by the flow session execution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("outputs")]
	public System.Nullable<System.Guid> Outputs
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("outputs");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("outputs_name")]
	public string Outputs_Name
	{
		get
		{
			return this.GetAttributeValue<string>("outputs_name");
		}
	}
	
	/// <summary>
	/// Date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// Owner Id
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// Name of the owner
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridname")]
	public string OwnerIdName
	{
		get
		{
			if (this.FormattedValues.Contains("ownerid"))
			{
				return this.FormattedValues["ownerid"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Yomi name of the owner
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridyominame")]
	public string OwnerIdYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("ownerid"))
			{
				return this.FormattedValues["ownerid"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Unique identifier for the business unit that owns the record
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunitname")]
	public string OwningBusinessUnitName
	{
		get
		{
			if (this.FormattedValues.Contains("owningbusinessunit"))
			{
				return this.FormattedValues["owningbusinessunit"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Unique identifier for the team that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// Unique identifier for the user that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// The sequence id of the parent cloud flow run, only used when the Desktop Flow was run by a cloud flow.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentcloudflowrunsequenceid")]
	public string ParentCloudFlowRunSequenceId
	{
		get
		{
			return this.GetAttributeValue<string>("parentcloudflowrunsequenceid");
		}
		set
		{
			this.OnPropertyChanging("ParentCloudFlowRunSequenceId");
			this.SetAttributeValue("parentcloudflowrunsequenceid", value);
			this.OnPropertyChanged("ParentCloudFlowRunSequenceId");
		}
	}
	
	/// <summary>
	/// The run id of the parent desktop flow run, only used when the Desktop Flow was run by a desktop flow. Used instead of Parent Desktop Flow Run Id when the field is available. Same purpose but keeping only the guid instead of doing a lookup.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentdesktopflowrunguid")]
	public System.Nullable<System.Guid> ParentDesktopFlowRunGuid
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("parentdesktopflowrunguid");
		}
		set
		{
			this.OnPropertyChanging("ParentDesktopFlowRunGuid");
			this.SetAttributeValue("parentdesktopflowrunguid", value);
			this.OnPropertyChanged("ParentDesktopFlowRunGuid");
		}
	}
	
	/// <summary>
	/// The run id of the parent desktop flow run, only used when the Desktop Flow was run by a desktop flow.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentdesktopflowrunid")]
	public Microsoft.Xrm.Sdk.EntityReference ParentDesktopFlowRunId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("parentdesktopflowrunid");
		}
		set
		{
			this.OnPropertyChanging("ParentDesktopFlowRunId");
			this.SetAttributeValue("parentdesktopflowrunid", value);
			this.OnPropertyChanged("ParentDesktopFlowRunId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentdesktopflowrunidname")]
	public string parentdesktopflowrunidName
	{
		get
		{
			if (this.FormattedValues.Contains("parentdesktopflowrunid"))
			{
				return this.FormattedValues["parentdesktopflowrunid"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Id of the parent workflow, cloud flow or desktop flow.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentworkflowid")]
	public string ParentWorkflowId
	{
		get
		{
			return this.GetAttributeValue<string>("parentworkflowid");
		}
		set
		{
			this.OnPropertyChanging("ParentWorkflowId");
			this.SetAttributeValue("parentworkflowid", value);
			this.OnPropertyChanged("ParentWorkflowId");
		}
	}
	
	/// <summary>
	/// The version of the process with which the flow session is associated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processversion")]
	public string ProcessVersion
	{
		get
		{
			return this.GetAttributeValue<string>("processversion");
		}
		set
		{
			this.OnPropertyChanging("ProcessVersion");
			this.SetAttributeValue("processversion", value);
			this.OnPropertyChanged("ProcessVersion");
		}
	}
	
	/// <summary>
	/// Unique identifier of the process with which the flow session is associated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
	public Microsoft.Xrm.Sdk.EntityReference RegardingObjectId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("regardingobjectid");
		}
		set
		{
			this.OnPropertyChanging("RegardingObjectId");
			this.SetAttributeValue("regardingobjectid", value);
			this.OnPropertyChanged("RegardingObjectId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectidname")]
	public string RegardingObjectIdName
	{
		get
		{
			if (this.FormattedValues.Contains("regardingobjectid"))
			{
				return this.FormattedValues["regardingobjectid"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectidyominame")]
	public string RegardingObjectIdYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("regardingobjectid"))
			{
				return this.FormattedValues["regardingobjectid"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Details about the run.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rundetails")]
	public string RunDetails
	{
		get
		{
			return this.GetAttributeValue<string>("rundetails");
		}
		set
		{
			this.OnPropertyChanging("RunDetails");
			this.SetAttributeValue("rundetails", value);
			this.OnPropertyChanged("RunDetails");
		}
	}
	
	/// <summary>
	/// Duration of the run.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("runduration")]
	public System.Nullable<long> RunDuration
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("runduration");
		}
		set
		{
			this.OnPropertyChanging("RunDuration");
			this.SetAttributeValue("runduration", value);
			this.OnPropertyChanged("RunDuration");
		}
	}
	
	/// <summary>
	/// Duration of the run execution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("runexecutionduration")]
	public System.Nullable<long> RunExecutionDuration
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("runexecutionduration");
		}
		set
		{
			this.OnPropertyChanging("RunExecutionDuration");
			this.SetAttributeValue("runexecutionduration", value);
			this.OnPropertyChanged("RunExecutionDuration");
		}
	}
	
	/// <summary>
	/// Indicates the run mode of the desktop flow run.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("runmode")]
	public virtual flowsession_runmode? RunMode
	{
		get
		{
			return ((flowsession_runmode?)(EntityOptionSetEnum.GetEnum(this, "runmode")));
		}
		set
		{
			this.OnPropertyChanging("RunMode");
			this.SetAttributeValue("runmode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("RunMode");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("runmodename")]
	public string runmodeName
	{
		get
		{
			if (this.FormattedValues.Contains("runmode"))
			{
				return this.FormattedValues["runmode"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Indicates the run session mode of the desktop flow run.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("runsessionmode")]
	public virtual flowsession_runsessionmode? RunSessionMode
	{
		get
		{
			return ((flowsession_runsessionmode?)(EntityOptionSetEnum.GetEnum(this, "runsessionmode")));
		}
		set
		{
			this.OnPropertyChanging("RunSessionMode");
			this.SetAttributeValue("runsessionmode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("RunSessionMode");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("runsessionmodename")]
	public string runsessionmodeName
	{
		get
		{
			if (this.FormattedValues.Contains("runsessionmode"))
			{
				return this.FormattedValues["runsessionmode"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Time the run spent waiting.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("runwaitduration")]
	public System.Nullable<long> RunWaitDuration
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("runwaitduration");
		}
		set
		{
			this.OnPropertyChanging("RunWaitDuration");
			this.SetAttributeValue("runwaitduration", value);
			this.OnPropertyChanged("RunWaitDuration");
		}
	}
	
	/// <summary>
	/// The username used in the Desktop Flow run.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sessionusername")]
	public string SessionUsername
	{
		get
		{
			return this.GetAttributeValue<string>("sessionusername");
		}
		set
		{
			this.OnPropertyChanging("SessionUsername");
			this.SetAttributeValue("sessionusername", value);
			this.OnPropertyChanged("SessionUsername");
		}
	}
	
	/// <summary>
	/// The SID of the user used in the Desktop Flow run.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sessionusersid")]
	public string SessionUserSID
	{
		get
		{
			return this.GetAttributeValue<string>("sessionusersid");
		}
		set
		{
			this.OnPropertyChanging("SessionUserSID");
			this.SetAttributeValue("sessionusersid", value);
			this.OnPropertyChanged("SessionUserSID");
		}
	}
	
	/// <summary>
	/// The date and time at which the flow session was started.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("startedon")]
	public System.Nullable<System.DateTime> StartedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("startedon");
		}
		set
		{
			this.OnPropertyChanging("StartedOn");
			this.SetAttributeValue("startedon", value);
			this.OnPropertyChanged("StartedOn");
		}
	}
	
	/// <summary>
	/// Status of the FlowSession
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual flowsession_statecode? statecode
	{
		get
		{
			return ((flowsession_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
	public string statecodeName
	{
		get
		{
			if (this.FormattedValues.Contains("statecode"))
			{
				return this.FormattedValues["statecode"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Reason for the status of the FlowSession
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual flowsession_statuscode? statuscode
	{
		get
		{
			return ((flowsession_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
	public string statuscodeName
	{
		get
		{
			if (this.FormattedValues.Contains("statuscode"))
			{
				return this.FormattedValues["statuscode"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Sub-Category of the flow session.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("subcategory")]
	public virtual flowsession_subcategory? SubCategory
	{
		get
		{
			return ((flowsession_subcategory?)(EntityOptionSetEnum.GetEnum(this, "subcategory")));
		}
		set
		{
			this.OnPropertyChanging("SubCategory");
			this.SetAttributeValue("subcategory", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("SubCategory");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("subcategoryname")]
	public string subcategoryName
	{
		get
		{
			if (this.FormattedValues.Contains("subcategory"))
			{
				return this.FormattedValues["subcategory"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Indicates the type of trigger used to run the desktop flow.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("triggertype")]
	public virtual flowsession_triggertype? TriggerType
	{
		get
		{
			return ((flowsession_triggertype?)(EntityOptionSetEnum.GetEnum(this, "triggertype")));
		}
		set
		{
			this.OnPropertyChanging("TriggerType");
			this.SetAttributeValue("triggertype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("TriggerType");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("triggertypename")]
	public string triggertypeName
	{
		get
		{
			if (this.FormattedValues.Contains("triggertype"))
			{
				return this.FormattedValues["triggertype"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Time zone code that was in use when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// 1:N flowsession_flowsession_parentdesktopflowrunid
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("flowsession_flowsession_parentdesktopflowrunid", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
	public System.Collections.Generic.IEnumerable<flowsession> Referencedflowsession_flowsession_parentdesktopflowrunid
	{
		get
		{
			return this.GetRelatedEntities<flowsession>("flowsession_flowsession_parentdesktopflowrunid", Microsoft.Xrm.Sdk.EntityRole.Referenced);
		}
		set
		{
			this.OnPropertyChanging("Referencedflowsession_flowsession_parentdesktopflowrunid");
			this.SetRelatedEntities<flowsession>("flowsession_flowsession_parentdesktopflowrunid", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
			this.OnPropertyChanged("Referencedflowsession_flowsession_parentdesktopflowrunid");
		}
	}
	
	/// <summary>
	/// N:1 flowsession_flowsession_parentdesktopflowrunid
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentdesktopflowrunid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("flowsession_flowsession_parentdesktopflowrunid", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
	public flowsession Referencingflowsession_flowsession_parentdesktopflowrunid
	{
		get
		{
			return this.GetRelatedEntity<flowsession>("flowsession_flowsession_parentdesktopflowrunid", Microsoft.Xrm.Sdk.EntityRole.Referencing);
		}
		set
		{
			this.OnPropertyChanging("Referencingflowsession_flowsession_parentdesktopflowrunid");
			this.SetRelatedEntity<flowsession>("flowsession_flowsession_parentdesktopflowrunid", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
			this.OnPropertyChanged("Referencingflowsession_flowsession_parentdesktopflowrunid");
		}
	}
}
#pragma warning restore CS1591
