#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Status of the script session.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum processsession_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Incomplete = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Complete = 1,
}

/// <summary>
/// Additional information about status of the script session.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum processsession_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	NotStarted = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	InProgress = 2,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Paused = 3,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Completed = 4,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Canceled = 5,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Failed = 6,
}

/// <summary>
/// Information that is generated when a dialog is run. Every time that you run a dialog, a dialog session is created.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("processsession")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class ProcessSession : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
				/// <summary>
		/// Available fields, a the time of codegen, for the processsession entity
		/// </summary>
		public partial class Fields
		{
			public const string ActivityName = "activityname";
			public const string CanceledBy = "canceledby";
			public const string CanceledByName = "canceledbyname";
			public const string CanceledByYomiName = "canceledbyyominame";
			public const string CanceledOn = "canceledon";
			public const string Comments = "comments";
			public const string CompletedBy = "completedby";
			public const string CompletedByName = "completedbyname";
			public const string CompletedByYomiName = "completedbyyominame";
			public const string CompletedOn = "completedon";
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedByYomiName = "createdbyyominame";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string ErrorCode = "errorcode";
			public const string ExecutedBy = "executedby";
			public const string ExecutedByName = "executedbyname";
			public const string ExecutedByYomiName = "executedbyyominame";
			public const string ExecutedOn = "executedon";
			public const string InputArguments = "inputarguments";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedByYomiName = "modifiedbyyominame";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string Name = "name";
			public const string NextLinkedSessionId = "nextlinkedsessionid";
			public const string NextLinkedSessionIdName = "nextlinkedsessionidname";
			public const string OriginatingSessionId = "originatingsessionid";
			public const string OriginatingSessionIdName = "originatingsessionidname";
			public const string OwnerId = "ownerid";
			public const string OwnerIdName = "owneridname";
			public const string OwnerIdYomiName = "owneridyominame";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningBusinessUnitName = "owningbusinessunitname";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string PreviousLinkedSessionId = "previouslinkedsessionid";
			public const string PreviousLinkedSessionIdName = "previouslinkedsessionidname";
			public const string ProcessId = "processid";
			public const string ProcessIdName = "processidname";
			public const string ProcessSessionId = "processsessionid";
			public const string Id = "processsessionid";
			public const string ProcessStageName = "processstagename";
			public const string ProcessState = "processstate";
			public const string RegardingObjectId = "regardingobjectid";
			public const string RegardingObjectIdName = "regardingobjectidname";
			public const string RegardingObjectIdYomiName = "regardingobjectidyominame";
			public const string StartedBy = "startedby";
			public const string StartedByName = "startedbyname";
			public const string StartedByYomiName = "startedbyyominame";
			public const string StartedOn = "startedon";
			public const string StateCode = "statecode";
			public const string StateCodeName = "statecodename";
			public const string StatusCode = "statuscode";
			public const string StatusCodeName = "statuscodename";
			public const string StepName = "stepname";
			public const string Referencedlk_processsession_nextlinkedsessionid = "Referencedlk_processsession_nextlinkedsessionid";
			public const string Referencedlk_processsession_originatingsessionid = "Referencedlk_processsession_originatingsessionid";
			public const string Referencedlk_processsession_previouslinkedsessionid = "Referencedlk_processsession_previouslinkedsessionid";
			public const string Referencinglk_processsession_nextlinkedsessionid = "lk_processsession_nextlinkedsessionid";
			public const string Referencinglk_processsession_originatingsessionid = "lk_processsession_originatingsessionid";
			public const string Referencinglk_processsession_previouslinkedsessionid = "lk_processsession_previouslinkedsessionid";
		}
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public ProcessSession() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "processsession";
	
	public const string EntityLogicalCollectionName = "processsessions";
	
	public const string EntitySetName = "processsessions";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// Name of the activity that is being executed.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("activityname")]
	public string ActivityName
	{
		get
		{
			return this.GetAttributeValue<string>("activityname");
		}
		set
		{
			this.OnPropertyChanging("ActivityName");
			this.SetAttributeValue("activityname", value);
			this.OnPropertyChanged("ActivityName");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who canceled the dialog session.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("canceledby")]
	public Microsoft.Xrm.Sdk.EntityReference CanceledBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("canceledby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("canceledbyname")]
	public string CanceledByName
	{
		get
		{
			if (this.FormattedValues.Contains("canceledby"))
			{
				return this.FormattedValues["canceledby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("canceledbyyominame")]
	public string CanceledByYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("canceledby"))
			{
				return this.FormattedValues["canceledby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Date and time when the dialog session was canceled.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("canceledon")]
	public System.Nullable<System.DateTime> CanceledOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("canceledon");
		}
		set
		{
			this.OnPropertyChanging("CanceledOn");
			this.SetAttributeValue("canceledon", value);
			this.OnPropertyChanged("CanceledOn");
		}
	}
	
	/// <summary>
	/// User comments.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("comments")]
	public string Comments
	{
		get
		{
			return this.GetAttributeValue<string>("comments");
		}
		set
		{
			this.OnPropertyChanging("Comments");
			this.SetAttributeValue("comments", value);
			this.OnPropertyChanged("Comments");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who completed the dialog session.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("completedby")]
	public Microsoft.Xrm.Sdk.EntityReference CompletedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("completedby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("completedbyname")]
	public string CompletedByName
	{
		get
		{
			if (this.FormattedValues.Contains("completedby"))
			{
				return this.FormattedValues["completedby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("completedbyyominame")]
	public string CompletedByYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("completedby"))
			{
				return this.FormattedValues["completedby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Date and time when the dialog session was completed.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("completedon")]
	public System.Nullable<System.DateTime> CompletedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("completedon");
		}
		set
		{
			this.OnPropertyChanging("CompletedOn");
			this.SetAttributeValue("completedon", value);
			this.OnPropertyChanged("CompletedOn");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who started the dialog session.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
	public string CreatedByName
	{
		get
		{
			if (this.FormattedValues.Contains("createdby"))
			{
				return this.FormattedValues["createdby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
	public string CreatedByYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("createdby"))
			{
				return this.FormattedValues["createdby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Date and time when the dialog session was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the dialog session.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
	public string CreatedOnBehalfByName
	{
		get
		{
			if (this.FormattedValues.Contains("createdonbehalfby"))
			{
				return this.FormattedValues["createdonbehalfby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
	public string CreatedOnBehalfByYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("createdonbehalfby"))
			{
				return this.FormattedValues["createdonbehalfby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Error code related to the dialog session.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("errorcode")]
	public System.Nullable<int> ErrorCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("errorcode");
		}
		set
		{
			this.OnPropertyChanging("ErrorCode");
			this.SetAttributeValue("errorcode", value);
			this.OnPropertyChanged("ErrorCode");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who ran the dialog process.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("executedby")]
	public Microsoft.Xrm.Sdk.EntityReference ExecutedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("executedby");
		}
		set
		{
			this.OnPropertyChanging("ExecutedBy");
			this.SetAttributeValue("executedby", value);
			this.OnPropertyChanged("ExecutedBy");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("executedbyname")]
	public string ExecutedByName
	{
		get
		{
			if (this.FormattedValues.Contains("executedby"))
			{
				return this.FormattedValues["executedby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("executedbyyominame")]
	public string ExecutedByYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("executedby"))
			{
				return this.FormattedValues["executedby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Date and time when the dialog process was run.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("executedon")]
	public System.Nullable<System.DateTime> ExecutedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("executedon");
		}
	}
	
	/// <summary>
	/// Input arguments for the child dialog process.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("inputarguments")]
	public string InputArguments
	{
		get
		{
			return this.GetAttributeValue<string>("inputarguments");
		}
		set
		{
			this.OnPropertyChanging("InputArguments");
			this.SetAttributeValue("inputarguments", value);
			this.OnPropertyChanged("InputArguments");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who last modified the dialog session.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
	public string ModifiedByName
	{
		get
		{
			if (this.FormattedValues.Contains("modifiedby"))
			{
				return this.FormattedValues["modifiedby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
	public string ModifiedByYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("modifiedby"))
			{
				return this.FormattedValues["modifiedby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Date and time when the dialog session was last modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the dialog session.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
	public string ModifiedOnBehalfByName
	{
		get
		{
			if (this.FormattedValues.Contains("modifiedonbehalfby"))
			{
				return this.FormattedValues["modifiedonbehalfby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
	public string ModifiedOnBehalfByYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("modifiedonbehalfby"))
			{
				return this.FormattedValues["modifiedonbehalfby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Name of the dialog session.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
	public string Name
	{
		get
		{
			return this.GetAttributeValue<string>("name");
		}
		set
		{
			this.OnPropertyChanging("Name");
			this.SetAttributeValue("name", value);
			this.OnPropertyChanged("Name");
		}
	}
	
	/// <summary>
	/// Unique identifier of the succeeding linked dialog session.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nextlinkedsessionid")]
	public Microsoft.Xrm.Sdk.EntityReference NextLinkedSessionId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("nextlinkedsessionid");
		}
		set
		{
			this.OnPropertyChanging("NextLinkedSessionId");
			this.SetAttributeValue("nextlinkedsessionid", value);
			this.OnPropertyChanged("NextLinkedSessionId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nextlinkedsessionidname")]
	public string NextLinkedSessionIdName
	{
		get
		{
			if (this.FormattedValues.Contains("nextlinkedsessionid"))
			{
				return this.FormattedValues["nextlinkedsessionid"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Unique identifier of the originating dialog session.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("originatingsessionid")]
	public Microsoft.Xrm.Sdk.EntityReference OriginatingSessionId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("originatingsessionid");
		}
		set
		{
			this.OnPropertyChanging("OriginatingSessionId");
			this.SetAttributeValue("originatingsessionid", value);
			this.OnPropertyChanged("OriginatingSessionId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("originatingsessionidname")]
	public string OriginatingSessionIdName
	{
		get
		{
			if (this.FormattedValues.Contains("originatingsessionid"))
			{
				return this.FormattedValues["originatingsessionid"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Unique identifier of the user or team who owns the dialog session.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridname")]
	public string OwnerIdName
	{
		get
		{
			if (this.FormattedValues.Contains("ownerid"))
			{
				return this.FormattedValues["ownerid"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridyominame")]
	public string OwnerIdYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("ownerid"))
			{
				return this.FormattedValues["ownerid"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Unique identifier of the business unit that owns the dialog session.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunitname")]
	public string OwningBusinessUnitName
	{
		get
		{
			if (this.FormattedValues.Contains("owningbusinessunit"))
			{
				return this.FormattedValues["owningbusinessunit"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Unique identifier of the team who owns the dialog session.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who owns the dialog session.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// Unique identifier of the preceding linked dialog session.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("previouslinkedsessionid")]
	public Microsoft.Xrm.Sdk.EntityReference PreviousLinkedSessionId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("previouslinkedsessionid");
		}
		set
		{
			this.OnPropertyChanging("PreviousLinkedSessionId");
			this.SetAttributeValue("previouslinkedsessionid", value);
			this.OnPropertyChanged("PreviousLinkedSessionId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("previouslinkedsessionidname")]
	public string PreviousLinkedSessionIdName
	{
		get
		{
			if (this.FormattedValues.Contains("previouslinkedsessionid"))
			{
				return this.FormattedValues["previouslinkedsessionid"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Select the process activation record that is related to the dialog session.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processid")]
	public Microsoft.Xrm.Sdk.EntityReference ProcessId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("processid");
		}
		set
		{
			this.OnPropertyChanging("ProcessId");
			this.SetAttributeValue("processid", value);
			this.OnPropertyChanged("ProcessId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processidname")]
	public string ProcessIdName
	{
		get
		{
			if (this.FormattedValues.Contains("processid"))
			{
				return this.FormattedValues["processid"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Unique identifier of the dialog session.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processsessionid")]
	public System.Nullable<System.Guid> ProcessSessionId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("processsessionid");
		}
		set
		{
			this.OnPropertyChanging("ProcessSessionId");
			this.SetAttributeValue("processsessionid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("ProcessSessionId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processsessionid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.ProcessSessionId = value;
		}
	}
	
	/// <summary>
	/// Name of the dialog stage.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processstagename")]
	public string ProcessStageName
	{
		get
		{
			return this.GetAttributeValue<string>("processstagename");
		}
		set
		{
			this.OnPropertyChanging("ProcessStageName");
			this.SetAttributeValue("processstagename", value);
			this.OnPropertyChanged("ProcessStageName");
		}
	}
	
	/// <summary>
	/// State of the dialog process.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processstate")]
	public string ProcessState
	{
		get
		{
			return this.GetAttributeValue<string>("processstate");
		}
		set
		{
			this.OnPropertyChanging("ProcessState");
			this.SetAttributeValue("processstate", value);
			this.OnPropertyChanged("ProcessState");
		}
	}
	
	/// <summary>
	/// Unique identifier of the object with which the dialog session is associated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
	public Microsoft.Xrm.Sdk.EntityReference RegardingObjectId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("regardingobjectid");
		}
		set
		{
			this.OnPropertyChanging("RegardingObjectId");
			this.SetAttributeValue("regardingobjectid", value);
			this.OnPropertyChanged("RegardingObjectId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectidname")]
	public string RegardingObjectIdName
	{
		get
		{
			if (this.FormattedValues.Contains("regardingobjectid"))
			{
				return this.FormattedValues["regardingobjectid"];
			}
			else
			{
				return default(string);
			}
		}
		set
		{
			this.OnPropertyChanging("RegardingObjectIdName");
			this.SetAttributeValue("regardingobjectidname", value);
			this.OnPropertyChanged("RegardingObjectIdName");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectidyominame")]
	public string RegardingObjectIdYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("regardingobjectid"))
			{
				return this.FormattedValues["regardingobjectid"];
			}
			else
			{
				return default(string);
			}
		}
		set
		{
			this.OnPropertyChanging("RegardingObjectIdYomiName");
			this.SetAttributeValue("regardingobjectidyominame", value);
			this.OnPropertyChanged("RegardingObjectIdYomiName");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who started the dialog session.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("startedby")]
	public Microsoft.Xrm.Sdk.EntityReference StartedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("startedby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("startedbyname")]
	public string StartedByName
	{
		get
		{
			if (this.FormattedValues.Contains("startedby"))
			{
				return this.FormattedValues["startedby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("startedbyyominame")]
	public string StartedByYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("startedby"))
			{
				return this.FormattedValues["startedby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Date and time when the dialog session was started.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("startedon")]
	public System.Nullable<System.DateTime> StartedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("startedon");
		}
		set
		{
			this.OnPropertyChanging("StartedOn");
			this.SetAttributeValue("startedon", value);
			this.OnPropertyChanged("StartedOn");
		}
	}
	
	/// <summary>
	/// Status of the dialog session.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual processsession_statecode? StateCode
	{
		get
		{
			return ((processsession_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("StateCode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("StateCode");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
	public string StateCodeName
	{
		get
		{
			if (this.FormattedValues.Contains("statecode"))
			{
				return this.FormattedValues["statecode"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Reason for the status of the dialog session.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual processsession_statuscode? StatusCode
	{
		get
		{
			return ((processsession_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("StatusCode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("StatusCode");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
	public string StatusCodeName
	{
		get
		{
			if (this.FormattedValues.Contains("statuscode"))
			{
				return this.FormattedValues["statuscode"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Name of the dialog step.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stepname")]
	public string StepName
	{
		get
		{
			return this.GetAttributeValue<string>("stepname");
		}
		set
		{
			this.OnPropertyChanging("StepName");
			this.SetAttributeValue("stepname", value);
			this.OnPropertyChanged("StepName");
		}
	}
	
	/// <summary>
	/// 1:N lk_processsession_nextlinkedsessionid
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_processsession_nextlinkedsessionid", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
	public System.Collections.Generic.IEnumerable<ProcessSession> Referencedlk_processsession_nextlinkedsessionid
	{
		get
		{
			return this.GetRelatedEntities<ProcessSession>("lk_processsession_nextlinkedsessionid", Microsoft.Xrm.Sdk.EntityRole.Referenced);
		}
		set
		{
			this.OnPropertyChanging("Referencedlk_processsession_nextlinkedsessionid");
			this.SetRelatedEntities<ProcessSession>("lk_processsession_nextlinkedsessionid", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
			this.OnPropertyChanged("Referencedlk_processsession_nextlinkedsessionid");
		}
	}
	
	/// <summary>
	/// 1:N lk_processsession_originatingsessionid
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_processsession_originatingsessionid", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
	public System.Collections.Generic.IEnumerable<ProcessSession> Referencedlk_processsession_originatingsessionid
	{
		get
		{
			return this.GetRelatedEntities<ProcessSession>("lk_processsession_originatingsessionid", Microsoft.Xrm.Sdk.EntityRole.Referenced);
		}
		set
		{
			this.OnPropertyChanging("Referencedlk_processsession_originatingsessionid");
			this.SetRelatedEntities<ProcessSession>("lk_processsession_originatingsessionid", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
			this.OnPropertyChanged("Referencedlk_processsession_originatingsessionid");
		}
	}
	
	/// <summary>
	/// 1:N lk_processsession_previouslinkedsessionid
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_processsession_previouslinkedsessionid", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
	public System.Collections.Generic.IEnumerable<ProcessSession> Referencedlk_processsession_previouslinkedsessionid
	{
		get
		{
			return this.GetRelatedEntities<ProcessSession>("lk_processsession_previouslinkedsessionid", Microsoft.Xrm.Sdk.EntityRole.Referenced);
		}
		set
		{
			this.OnPropertyChanging("Referencedlk_processsession_previouslinkedsessionid");
			this.SetRelatedEntities<ProcessSession>("lk_processsession_previouslinkedsessionid", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
			this.OnPropertyChanged("Referencedlk_processsession_previouslinkedsessionid");
		}
	}
	
	/// <summary>
	/// N:1 lk_processsession_nextlinkedsessionid
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nextlinkedsessionid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_processsession_nextlinkedsessionid", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
	public ProcessSession Referencinglk_processsession_nextlinkedsessionid
	{
		get
		{
			return this.GetRelatedEntity<ProcessSession>("lk_processsession_nextlinkedsessionid", Microsoft.Xrm.Sdk.EntityRole.Referencing);
		}
		set
		{
			this.OnPropertyChanging("Referencinglk_processsession_nextlinkedsessionid");
			this.SetRelatedEntity<ProcessSession>("lk_processsession_nextlinkedsessionid", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
			this.OnPropertyChanged("Referencinglk_processsession_nextlinkedsessionid");
		}
	}
	
	/// <summary>
	/// N:1 lk_processsession_originatingsessionid
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("originatingsessionid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_processsession_originatingsessionid", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
	public ProcessSession Referencinglk_processsession_originatingsessionid
	{
		get
		{
			return this.GetRelatedEntity<ProcessSession>("lk_processsession_originatingsessionid", Microsoft.Xrm.Sdk.EntityRole.Referencing);
		}
		set
		{
			this.OnPropertyChanging("Referencinglk_processsession_originatingsessionid");
			this.SetRelatedEntity<ProcessSession>("lk_processsession_originatingsessionid", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
			this.OnPropertyChanged("Referencinglk_processsession_originatingsessionid");
		}
	}
	
	/// <summary>
	/// N:1 lk_processsession_previouslinkedsessionid
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("previouslinkedsessionid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_processsession_previouslinkedsessionid", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
	public ProcessSession Referencinglk_processsession_previouslinkedsessionid
	{
		get
		{
			return this.GetRelatedEntity<ProcessSession>("lk_processsession_previouslinkedsessionid", Microsoft.Xrm.Sdk.EntityRole.Referencing);
		}
		set
		{
			this.OnPropertyChanging("Referencinglk_processsession_previouslinkedsessionid");
			this.SetRelatedEntity<ProcessSession>("lk_processsession_previouslinkedsessionid", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
			this.OnPropertyChanged("Referencinglk_processsession_previouslinkedsessionid");
		}
	}
}
#pragma warning restore CS1591
