#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Status of the Power Pages Component
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum powerpagecomponent_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Reason for the status of the Power Pages Component
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum powerpagecomponent_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("powerpagecomponent")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class powerpagecomponent : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
				/// <summary>
		/// Available fields, a the time of codegen, for the powerpagecomponent entity
		/// </summary>
		public partial class Fields
		{
			public const string ComponentIdUnique = "componentidunique";
			public const string ComponentState = "componentstate";
			public const string componentstateName = "componentstatename";
			public const string content = "content";
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedByYomiName = "createdbyyominame";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string filecontent = "filecontent";
			public const string filecontent_Name = "filecontent_name";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string IsCustomizable = "iscustomizable";
			public const string IsManaged = "ismanaged";
			public const string ismanagedName = "ismanagedname";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedByYomiName = "modifiedbyyominame";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string name = "name";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OverwriteTime = "overwritetime";
			public const string OwnerId = "ownerid";
			public const string OwnerIdName = "owneridname";
			public const string OwnerIdYomiName = "owneridyominame";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningBusinessUnitName = "owningbusinessunitname";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string powerpagecomponentId = "powerpagecomponentid";
			public const string Id = "powerpagecomponentid";
			public const string powerpagecomponenttype = "powerpagecomponenttype";
			public const string powerpagecomponenttypeName = "powerpagecomponenttypename";
			public const string powerpagesiteid = "powerpagesiteid";
			public const string powerpagesiteidName = "powerpagesiteidname";
			public const string powerpagesitelanguageid = "powerpagesitelanguageid";
			public const string powerpagesitelanguageidName = "powerpagesitelanguageidname";
			public const string searchcontent = "searchcontent";
			public const string SolutionId = "solutionid";
			public const string statecode = "statecode";
			public const string statecodeName = "statecodename";
			public const string statuscode = "statuscode";
			public const string statuscodeName = "statuscodename";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string adx_invitation_mspp_webrole_powerpagecomponent = "adx_invitation_mspp_webrole_powerpagecomponent";
			public const string powerpagecomponent_mspp_webrole_contact = "powerpagecomponent_mspp_webrole_contact";
			public const string powerpagecomponent_powerpagecomponent = "powerpagecomponent_powerpagecomponent";
		}
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public powerpagecomponent() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "powerpagecomponent";
	
	public const string EntityLogicalCollectionName = "powerpagecomponents";
	
	public const string EntitySetName = "powerpagecomponents";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentidunique")]
	public System.Nullable<System.Guid> ComponentIdUnique
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("componentidunique");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
	public virtual componentstate? ComponentState
	{
		get
		{
			return ((componentstate?)(EntityOptionSetEnum.GetEnum(this, "componentstate")));
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstatename")]
	public string componentstateName
	{
		get
		{
			if (this.FormattedValues.Contains("componentstate"))
			{
				return this.FormattedValues["componentstate"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("content")]
	public string content
	{
		get
		{
			return this.GetAttributeValue<string>("content");
		}
		set
		{
			this.OnPropertyChanging("content");
			this.SetAttributeValue("content", value);
			this.OnPropertyChanged("content");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
	public string CreatedByName
	{
		get
		{
			if (this.FormattedValues.Contains("createdby"))
			{
				return this.FormattedValues["createdby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
	public string CreatedByYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("createdby"))
			{
				return this.FormattedValues["createdby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
	public string CreatedOnBehalfByName
	{
		get
		{
			if (this.FormattedValues.Contains("createdonbehalfby"))
			{
				return this.FormattedValues["createdonbehalfby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
	public string CreatedOnBehalfByYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("createdonbehalfby"))
			{
				return this.FormattedValues["createdonbehalfby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// File Content column contains portal web files e.g. png, css etc.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("filecontent")]
	public System.Nullable<System.Guid> filecontent
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("filecontent");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("filecontent_name")]
	public string filecontent_Name
	{
		get
		{
			return this.GetAttributeValue<string>("filecontent_name");
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iscustomizable")]
	public Microsoft.Xrm.Sdk.BooleanManagedProperty IsCustomizable
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.BooleanManagedProperty>("iscustomizable");
		}
		set
		{
			this.OnPropertyChanging("IsCustomizable");
			this.SetAttributeValue("iscustomizable", value);
			this.OnPropertyChanged("IsCustomizable");
		}
	}
	
	/// <summary>
	/// Indicates whether the solution component is part of a managed solution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanaged")]
	public System.Nullable<bool> IsManaged
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("ismanaged");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanagedname")]
	public string ismanagedName
	{
		get
		{
			if (this.FormattedValues.Contains("ismanaged"))
			{
				return this.FormattedValues["ismanaged"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
	public string ModifiedByName
	{
		get
		{
			if (this.FormattedValues.Contains("modifiedby"))
			{
				return this.FormattedValues["modifiedby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
	public string ModifiedByYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("modifiedby"))
			{
				return this.FormattedValues["modifiedby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
	public string ModifiedOnBehalfByName
	{
		get
		{
			if (this.FormattedValues.Contains("modifiedonbehalfby"))
			{
				return this.FormattedValues["modifiedonbehalfby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
	public string ModifiedOnBehalfByYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("modifiedonbehalfby"))
			{
				return this.FormattedValues["modifiedonbehalfby"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// The name of the custom entity.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
	public string name
	{
		get
		{
			return this.GetAttributeValue<string>("name");
		}
		set
		{
			this.OnPropertyChanging("name");
			this.SetAttributeValue("name", value);
			this.OnPropertyChanged("name");
		}
	}
	
	/// <summary>
	/// Date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overwritetime")]
	public System.Nullable<System.DateTime> OverwriteTime
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overwritetime");
		}
	}
	
	/// <summary>
	/// Owner Id
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// Name of the owner
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridname")]
	public string OwnerIdName
	{
		get
		{
			if (this.FormattedValues.Contains("ownerid"))
			{
				return this.FormattedValues["ownerid"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Yomi name of the owner
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridyominame")]
	public string OwnerIdYomiName
	{
		get
		{
			if (this.FormattedValues.Contains("ownerid"))
			{
				return this.FormattedValues["ownerid"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Unique identifier for the business unit that owns the record
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunitname")]
	public string OwningBusinessUnitName
	{
		get
		{
			if (this.FormattedValues.Contains("owningbusinessunit"))
			{
				return this.FormattedValues["owningbusinessunit"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Unique identifier for the team that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// Unique identifier for the user that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("powerpagecomponentid")]
	public System.Nullable<System.Guid> powerpagecomponentId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("powerpagecomponentid");
		}
		set
		{
			this.OnPropertyChanging("powerpagecomponentId");
			this.SetAttributeValue("powerpagecomponentid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("powerpagecomponentId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("powerpagecomponentid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.powerpagecomponentId = value;
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("powerpagecomponenttype")]
	public virtual powerpagecomponenttype? powerpagecomponenttype
	{
		get
		{
			return ((powerpagecomponenttype?)(EntityOptionSetEnum.GetEnum(this, "powerpagecomponenttype")));
		}
		set
		{
			this.OnPropertyChanging("powerpagecomponenttype");
			this.SetAttributeValue("powerpagecomponenttype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("powerpagecomponenttype");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("powerpagecomponenttypename")]
	public string powerpagecomponenttypeName
	{
		get
		{
			if (this.FormattedValues.Contains("powerpagecomponenttype"))
			{
				return this.FormattedValues["powerpagecomponenttype"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("powerpagesiteid")]
	public Microsoft.Xrm.Sdk.EntityReference powerpagesiteid
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("powerpagesiteid");
		}
		set
		{
			this.OnPropertyChanging("powerpagesiteid");
			this.SetAttributeValue("powerpagesiteid", value);
			this.OnPropertyChanged("powerpagesiteid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("powerpagesiteidname")]
	public string powerpagesiteidName
	{
		get
		{
			if (this.FormattedValues.Contains("powerpagesiteid"))
			{
				return this.FormattedValues["powerpagesiteid"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("powerpagesitelanguageid")]
	public Microsoft.Xrm.Sdk.EntityReference powerpagesitelanguageid
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("powerpagesitelanguageid");
		}
		set
		{
			this.OnPropertyChanging("powerpagesitelanguageid");
			this.SetAttributeValue("powerpagesitelanguageid", value);
			this.OnPropertyChanged("powerpagesitelanguageid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("powerpagesitelanguageidname")]
	public string powerpagesitelanguageidName
	{
		get
		{
			if (this.FormattedValues.Contains("powerpagesitelanguageid"))
			{
				return this.FormattedValues["powerpagesitelanguageid"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("searchcontent")]
	public string searchcontent
	{
		get
		{
			return this.GetAttributeValue<string>("searchcontent");
		}
		set
		{
			this.OnPropertyChanging("searchcontent");
			this.SetAttributeValue("searchcontent", value);
			this.OnPropertyChanged("searchcontent");
		}
	}
	
	/// <summary>
	/// Unique identifier of the associated solution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
	public System.Nullable<System.Guid> SolutionId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
		}
	}
	
	/// <summary>
	/// Status of the Power Pages Component
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual powerpagecomponent_statecode? statecode
	{
		get
		{
			return ((powerpagecomponent_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
	public string statecodeName
	{
		get
		{
			if (this.FormattedValues.Contains("statecode"))
			{
				return this.FormattedValues["statecode"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// Reason for the status of the Power Pages Component
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual powerpagecomponent_statuscode? statuscode
	{
		get
		{
			return ((powerpagecomponent_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
	public string statuscodeName
	{
		get
		{
			if (this.FormattedValues.Contains("statuscode"))
			{
				return this.FormattedValues["statuscode"];
			}
			else
			{
				return default(string);
			}
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Time zone code that was in use when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// N:N adx_invitation_mspp_webrole_powerpagecomponent
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_invitation_mspp_webrole_powerpagecomponent")]
	public System.Collections.Generic.IEnumerable<adx_invitation> adx_invitation_mspp_webrole_powerpagecomponent
	{
		get
		{
			return this.GetRelatedEntities<adx_invitation>("adx_invitation_mspp_webrole_powerpagecomponent", null);
		}
		set
		{
			this.OnPropertyChanging("adx_invitation_mspp_webrole_powerpagecomponent");
			this.SetRelatedEntities<adx_invitation>("adx_invitation_mspp_webrole_powerpagecomponent", null, value);
			this.OnPropertyChanged("adx_invitation_mspp_webrole_powerpagecomponent");
		}
	}
	
	/// <summary>
	/// N:N powerpagecomponent_mspp_webrole_contact
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("powerpagecomponent_mspp_webrole_contact")]
	public System.Collections.Generic.IEnumerable<Contact> powerpagecomponent_mspp_webrole_contact
	{
		get
		{
			return this.GetRelatedEntities<Contact>("powerpagecomponent_mspp_webrole_contact", null);
		}
		set
		{
			this.OnPropertyChanging("powerpagecomponent_mspp_webrole_contact");
			this.SetRelatedEntities<Contact>("powerpagecomponent_mspp_webrole_contact", null, value);
			this.OnPropertyChanged("powerpagecomponent_mspp_webrole_contact");
		}
	}
	
	/// <summary>
	/// N:N powerpagecomponent_powerpagecomponent
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("powerpagecomponent_powerpagecomponent", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
	public System.Collections.Generic.IEnumerable<powerpagecomponent> Referencingpowerpagecomponent_powerpagecomponent
	{
		get
		{
			return this.GetRelatedEntities<powerpagecomponent>("powerpagecomponent_powerpagecomponent", Microsoft.Xrm.Sdk.EntityRole.Referencing);
		}
		set
		{
			this.OnPropertyChanging("Referencingpowerpagecomponent_powerpagecomponent");
			this.SetRelatedEntities<powerpagecomponent>("powerpagecomponent_powerpagecomponent", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
			this.OnPropertyChanged("Referencingpowerpagecomponent_powerpagecomponent");
		}
	}
	
	/// <summary>
	/// N:N powerpagecomponent_powerpagecomponent
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("powerpagecomponent_powerpagecomponent", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
	public System.Collections.Generic.IEnumerable<powerpagecomponent> Referencedpowerpagecomponent_powerpagecomponent
	{
		get
		{
			return this.GetRelatedEntities<powerpagecomponent>("powerpagecomponent_powerpagecomponent", Microsoft.Xrm.Sdk.EntityRole.Referenced);
		}
		set
		{
			this.OnPropertyChanging("Referencedpowerpagecomponent_powerpagecomponent");
			this.SetRelatedEntities<powerpagecomponent>("powerpagecomponent_powerpagecomponent", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
			this.OnPropertyChanged("Referencedpowerpagecomponent_powerpagecomponent");
		}
	}
}
#pragma warning restore CS1591
